#!/usr/bin/env python
# SPDX-License-Identifier: Apache-2.0
"""Write a channel declaration with every raw segment string in a corpus, and no answers.

WHAT IT PROPOSES: NOTHING.

Every row comes out with `channel: null`, `basis: null` and `status: "opaque"`, and a
person fills them in. That is deliberate and it is the whole design of this tool.

A generator that guessed -- folding `Pulmonaty trunk` onto `Pulmonary trunk`, reading
`NRRD_DATASET_HYDROTHORAX/Segment_1` as an effusion, mapping `neo` to a SNOMED code --
would be right most of the time, and that is exactly what makes it dangerous. A reviewer
handed a filled-in table checks it the way people check filled-in forms: by looking for
something obviously wrong. A reviewer handed an empty table with the literal strings and
their counts has to decide each one, which is the work. `MOS-UI-149` makes this argument
about the curation console; it applies with more force here, because unlike a console
screen this output is committed and outlives the person who ran it.

It does one thing beyond listing: it renders every name through `repr()`, so
`'Pulmonary trunk '` is visibly different from `'Pulmonary trunk'`. A trailing space is
invisible in every other view of this data and is the difference between 92 cases and 91.

It also carries the three trust signals the source files record about themselves -- whether
the name is Slicer's default, whether Slicer's own `NameAutoGenerated` flag agrees, and the
annotation status -- as `_observed` members prefixed with an underscore, so a reader can see
what the file said without those facts being mistaken for decisions.

Usage:
    python medos/tools/ingest/channel_map_stub.py --root F:/... --corpus-id lung-nods-100 \\
        --out deploy/channelmap/lung-nods-100.json
"""

from __future__ import annotations

import argparse
import collections
import json
import re
import sys
from pathlib import Path
from typing import Any

try:
    import nrrd
except ImportError:  # pragma: no cover - import guard
    sys.exit("pynrrd is required.\n  pip install pynrrd")

TOOL = "medicalos-channel-map-stub"
SLICER_DEFAULT_NAME = re.compile(r"^Segment_\d+$")


def _raw_names(path: Path) -> dict[int, str]:
    """`Segment<N>_Name` exactly as the bytes spell it. See `_scan` for why."""
    with open(path, "rb") as handle:
        blob = handle.read(300_000)
    head = blob.split(b"\n\n", 1)[0].decode("utf-8", "replace")
    out: dict[int, str] = {}
    for line in head.split("\n"):
        match = re.match(r"^Segment(\d+)_Name:=(.*)$", line.rstrip("\r"))
        if match:
            out[int(match.group(1))] = match.group(2)
    return out


def _scan(root: Path) -> dict[str, dict[str, Any]]:
    """raw_name -> observed facts. Reads headers only; never prints a value."""
    found: dict[str, dict[str, Any]] = {}
    for path in sorted(root.rglob("*.seg.nrrd")):
        try:
            header = nrrd.read_header(str(path))
        except Exception:
            continue
        # THE LITERALS, read from the bytes. `nrrd.read_header` strips whitespace around
        # every value, so a name spelled `' neo'` comes back as `'neo'` and a declaration
        # written from the parsed form would silently cover two different strings with one
        # row. Measured: one file in NRRD_DATASET_LUNG_CANCER is exactly that case.
        literals = _raw_names(path)
        index = 0
        while f"Segment{index}_LabelValue" in header:
            raw = literals.get(index, str(header.get(f"Segment{index}_Name", "")))
            tags = str(header.get(f"Segment{index}_Tags", ""))
            status = re.search(r"Segmentation\.Status:([^|]*)", tags)
            term = re.search(r"TerminologyEntry:[^~]*~[^~]*~([^~]*)~", tags)
            entry = found.setdefault(
                raw,
                {
                    "observed_count": 0,
                    "_observed_is_slicer_default_name": bool(SLICER_DEFAULT_NAME.match(raw.strip())),
                    "_observed_name_auto_generated_flag": collections.Counter(),
                    "_observed_status": collections.Counter(),
                    "_observed_terminology": collections.Counter(),
                },
            )
            entry["observed_count"] += 1
            entry["_observed_name_auto_generated_flag"][
                str(header.get(f"Segment{index}_NameAutoGenerated", "0")).strip()
            ] += 1
            entry["_observed_status"][status.group(1).strip() if status else "(absent)"] += 1
            entry["_observed_terminology"][(term.group(1) if term else "(absent)").strip()] += 1
            index += 1
    return found


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog=TOOL, description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--root", required=True, metavar="DIR")
    p.add_argument("--corpus-id", required=True, metavar="ID")
    p.add_argument("--out", required=True, metavar="FILE")
    args = p.parse_args(argv)

    root = Path(args.root)
    if not root.is_dir():
        print(f"{TOOL}: --root {root} is not a directory", file=sys.stderr)
        return 2

    found = _scan(root)
    if not found:
        print(f"{TOOL}: no .seg.nrrd under {root}", file=sys.stderr)
        return 2

    rows = []
    for raw, facts in sorted(found.items(), key=lambda kv: (-kv[1]["observed_count"], kv[0])):
        rows.append(
            {
                "corpus_id": args.corpus_id,
                "raw_name": raw,
                "observed_count": facts["observed_count"],
                # The three answers a person owes. Left null on purpose.
                "channel": None,
                "basis": None,
                "status": "opaque",
                "declared_by": None,
                # What the FILE said, kept separate from what a person decides.
                "_observed_is_slicer_default_name": facts["_observed_is_slicer_default_name"],
                "_observed_name_auto_generated_flag": dict(facts["_observed_name_auto_generated_flag"]),
                "_observed_status": dict(facts["_observed_status"]),
                "_observed_terminology": dict(facts["_observed_terminology"].most_common(4)),
            }
        )

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        json.dumps(
            {
                "_tool": TOOL,
                "_note": (
                    "Every row needs a `channel`, a `basis` from medos/medos/training/channelmap.py's "
                    "closed enum, and a `status`. Nothing here is proposed: see this tool's "
                    "docstring for why a generator that guessed would be worse than one that "
                    "does not. Members prefixed `_` are observations from the files and are "
                    "ignored by the loader."
                ),
                "rows": rows,
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
        encoding="utf-8",
    )

    print("-" * 82)
    print(f"{TOOL}   corpus {args.corpus_id}")
    print("-" * 82)
    for row in rows:
        marker = "  (Slicer default -- this name is the ABSENCE of a name)" if row[
            "_observed_is_slicer_default_name"] else ""
        print(f"  {row['observed_count']:5d}  {row['raw_name']!r}{marker}")
    print("-" * 82)
    print(f"  {len(rows)} distinct raw name(s) -> {out}")
    print(f"  every `channel` is null. Nothing will resolve until a person fills them in.")
    print("-" * 82)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
