#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# -*- coding: utf-8 -*-
"""Scrub PHI out of 3D Slicer sidecar files (.mrml scenes, .nrrd headers).

WHY THIS TOOL EXISTS
--------------------
The NRRD *volumes* in the PulmoAI corpora are clean: the leak is entirely in the
Slicer sidecars.  A `.mrml` scene is a full XML dump of the Slicer subject
hierarchy, so it carries the DICOM attributes Slicer imported - patient name,
patient ID, birth date, study date - plus every filesystem path the annotator's
laptop happened to use.  A `.seg.nrrd` header carries `SegmentN_ID`, which Slicer
derives from the source model name and which therefore inherits the same string.

WHY PSEUDONYMISE RATHER THAN DELETE
-----------------------------------
Deleting `uids=` breaks the scene: Slicer uses those UIDs to bind a loaded volume
back to its DICOM series, and a segmentation whose referenced series UID is gone
loads as an orphan.  More importantly, spec chapter 03 (`docs/spec/03-medical-data-plane.md`)
makes consistent remapping a *blocking invariant*:

  MOS-DATA-031  UID remapping MUST be deterministic, consistent and reversible
                within a tenant.  For a fixed (tenant_id, deid_key_version) the
                same source UID MUST map to the same de-identified UID forever,
                across processes, restarts and re-ingests, and two distinct
                source UIDs MUST NEVER map to the same de-identified UID.
                Per-invocation or per-export random remapping is forbidden.
  MOS-DATA-032  The de-identified UID MUST be generated by
                `2.25.<int(uuid_from_hmac_sha256(tenant_deid_key, source_uid))>`.
  MOS-DATA-033  The mapping table is authoritative; MOS-DATA-032 is the generator
                that allows it to be rebuilt.  A generated UID that collides with
                an existing row for a *different* source UID MUST abort.
  MOS-DATA-034  A UID under the `1.2.840.10008` DICOM-registered root MUST be
                copied unchanged; every other UID MUST be remapped.
  MOS-DATA-037  De-identification MUST fail closed - never emit a partially
                de-identified object.

Concretely: a `ResultBundle` references source SOP Instance UIDs, and a
`DatasetVersion` is a content-addressed manifest of SOP Instance UIDs.  If this
script remapped per-file or per-run, every segmentation in the corpus would point
at UIDs that no longer exist and every dataset manifest hash would change on every
export.  Nothing would raise; the failure surfaces months later as an overlay that
does not line up.  Hence one process-wide, key-derived, collision-checked map.

WHY THE REPORT CONTAINS NO PHI
------------------------------
A de-identification report that quotes what it removed is itself a PHI disclosure,
and reports get mailed around.  Every removed value is referenced only by
`phi_ref`, a salted HMAC prefix, so two findings can be correlated without the
report carrying the value.  Path components that themselves contain PHI markers
are redacted the same way.

DEPENDENCIES
------------
numpy and pynrrd only (see requirements.txt next to this file).  pynrrd is used
solely to *verify* a rewritten NRRD header round-trips - the rewrite itself is
done on raw bytes so pixel data is never decoded, re-encoded, or touched.

SAFETY
------
Dry run by default.  `--apply` is required to write, every write is preceded by a
copy into `--backup-dir`, and the run aborts before touching anything if any
backup target already exists.

That last refusal is also the re-application guard.  UID remapping and surrogate
allocation are idempotent (the map is reloaded, our own tokens are recognised),
but `--date-policy shift` is not: a shifted date is shaped exactly like a real
one, so applying twice would shift twice.  Refusing to reuse a backup directory
is what makes that impossible.  Use `--date-policy redact` if you need a
transform that is safe to re-run.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import hmac
import io
import json
import os
import re
import secrets
import shutil
import stat
import sys
import unicodedata
import urllib.parse
import uuid
import xml.etree.ElementTree as ET
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterator, Sequence

try:
    import nrrd  # type: ignore
except ImportError as exc:  # pragma: no cover - explicit, actionable failure
    raise SystemExit(
        "pynrrd is required for NRRD header verification.\n"
        "  pip install pynrrd\n"
        f"(import failed: {exc})"
    ) from exc

try:
    import numpy as np  # type: ignore
except ImportError as exc:  # pragma: no cover
    raise SystemExit(f"numpy is required.\n  pip install numpy\n(import failed: {exc})") from exc


TOOL_NAME = "medicalos-scrub-slicer-scenes"
TOOL_VERSION = "1.0.0"

# --------------------------------------------------------------------------- #
# DEFAULTS - the only place in this file that may name a concrete location.
# --------------------------------------------------------------------------- #
DEFAULTS: dict[str, Any] = {
    # Dataset roots scanned when --root is not given.  Read-only.
    "roots": [
        r"F:/WorkSpace/PulmoAI/lungs/NRRD_DATASET_PNEUMONIA/CT_pheumonia",
        r"F:/WorkSpace/PulmoAI/NRRD_DATASET_HYDROTHORAX",
    ],
    # Everything the tool writes lives under this directory, which MUST be
    # outside every dataset root (enforced, not merely documented).
    "work_dir": r"D:/PycharmProjects/MedOS/.deid",
    "backup_subdir": "backup",
    "key_name": "deid_secret.key",
    "map_name": "uid_map.jsonl",
    "report_name": "scrub_report.json",
    # Detection tuning.
    "mrn_min_digits": 7,
    "mrn_max_digits": 12,
    "date_min_year": 1900,
    "date_max_year": 2100,
    "date_shift_window_days": 365,
    # Filenames whose *contents* we parse.
    "mrml_glob": "*.mrml",
    "nrrd_glob": "*.nrrd",
}

# Directories/files that are macOS archive noise, not data.
SKIP_PATH_PARTS = frozenset({"__MACOSX"})
SKIP_NAME_PREFIXES = ("._",)

# DICOM-registered root: MUST be copied unchanged (MOS-DATA-034).
DICOM_WELL_KNOWN_UID_ROOT = "1.2.840.10008"


class ScrubError(RuntimeError):
    """Raised for any condition that must abort the run loudly (MOS-DATA-037)."""


# --------------------------------------------------------------------------- #
# Categories.  Every finding carries exactly one; the report aggregates by it.
# --------------------------------------------------------------------------- #
CAT_PATIENT_NAME = "patient_name"
CAT_PATIENT_ID = "patient_id"
CAT_SITE_TOKEN = "site_token"
CAT_PSEUDONYM = "pseudonym"
CAT_ACCESSION = "accession_token"
CAT_LOCAL_USER_PATH = "local_user_path"
CAT_CYRILLIC_TEXT = "cyrillic_text"
CAT_FILESYSTEM_PATH = "filesystem_path"
CAT_DICOM_UID = "dicom_uid"
CAT_DATE = "date"

# Categories that mean "an identifier is still sitting in the file".  `date` and
# `dicom_uid` are deliberately absent: a shifted date is indistinguishable from a
# real one, and a remapped UID is still UID-shaped, so neither can be used as
# evidence that a file was missed.  --verify asserts on this set.
RESIDUAL_CATEGORIES = frozenset(
    {
        "patient_name",
        "patient_id",
        "site_token",
        "pseudonym",
        "accession_token",
        "local_user_path",
        "cyrillic_text",
        "filesystem_path",
    }
)

ALL_CATEGORIES = (
    CAT_PATIENT_NAME,
    CAT_PATIENT_ID,
    CAT_SITE_TOKEN,
    CAT_PSEUDONYM,
    CAT_ACCESSION,
    CAT_LOCAL_USER_PATH,
    CAT_CYRILLIC_TEXT,
    CAT_FILESYSTEM_PATH,
    CAT_DICOM_UID,
    CAT_DATE,
)


# --------------------------------------------------------------------------- #
# Patterns
# --------------------------------------------------------------------------- #
RE_SITE_TOKEN = re.compile(r"\bMEDSI\b", re.IGNORECASE)
RE_PSEUDONYM = re.compile(r"\bSVR[_-]\d{3,}\b", re.IGNORECASE)
RE_UNNAMED = re.compile(r"\bUnnamed\s*[-_]\s*(\d{5,})\b", re.IGNORECASE)
# `/Users/<login>`, `\Users\<login>`, `/home/<login>`.  The backreference keeps
# the separator consistent so a Windows path is rebuilt as a Windows path.
RE_USER_HOME = re.compile(r"([/\\])(Users|home)\1([^/\\\s\"']{1,64})")
USER_SURROGATE = "USER_X"
RE_CYRILLIC_RUN = re.compile(r"[\u0400-\u04FF]{3,}")
RE_DIGIT_RUN = re.compile(r"(?<![\d.])(\d{4,14})(?![\d.])")
# A DICOM UID is rooted at an ISO arc (0, 1 or 2) and is at least 12 characters.
# Without the root anchor and the length floor this also matches the Slicer
# version string `5.6.1` and remapping that silently corrupts the scene.
RE_UID = re.compile(r"(?<![\d.])([0-2](?:\.\d+){2,})(?![\d.])")
UID_MIN_LEN = 12
UID_MAX_LEN = 64

# Tokens this tool itself emits.  Recognising them keeps re-runs idempotent: a
# second pass must not pseudonymise a pseudonym into a different pseudonym.
RE_NEUTRAL_TOKEN = re.compile(r"^(?:CASE_\d{4}(?:_[0-9a-f]{4})?|SITE_X|TEXT_REDACTED)$")


def is_dicom_uid(text: str) -> bool:
    """True for values that are plausibly DICOM UIDs, not version numbers."""
    return bool(RE_UID.fullmatch(text)) and UID_MIN_LEN <= len(text) <= UID_MAX_LEN
RE_PURE_NUMERIC = re.compile(r"^[\s\d.eE+\-,()]*$")
RE_PERCENT_ESCAPE = re.compile(r"%[0-9A-Fa-f]{2}")
RE_PATH_LIKE = re.compile(
    r"(^[A-Za-z]:[\\/])"                     # C:\ or C:/
    r"|(^\.{1,2}[\\/])"                      # ./ or ../
    r"|(^[\\/])"                             # /abs or \abs
    r"|([\\/][^\\/]*\.(?:nrrd|nhdr|mrml|vtk|vtp|stl|ply|ctbl|dcm|ima|png|json|seg)\b)",
    re.IGNORECASE,
)
RE_FILE_EXT = re.compile(r"(\.(?:seg\.nrrd|nrrd|nhdr|mrml|vtk|vtp|stl|ply|ctbl|dcm|ima|png|json))$", re.IGNORECASE)

# A word that could be part of a personal name: >=2 letters, Latin or Cyrillic,
# starting uppercase (either "Ivanov" or "IVANOV").  Used only to widen a span
# that already contains a hard marker.
RE_NAME_WORD = re.compile(r"^[A-Z\u0410-\u042F][A-Za-z\u0400-\u04FF'\u2019`.-]{1,}$")

# Attribute names whose value is a filesystem path.
RE_PATH_ATTR = re.compile(r"^(fileName|uri|fileListMember\d+|fileListMemberURI\d+)$")

# Attributes that are internal Slicer plumbing: node ids, references, layout.
# Scrubbing them would corrupt the scene and they never carry PHI.
SKIP_ATTRS = frozenset(
    {
        "id",
        "references",
        "AxisLabels",
        "orientationMatrixAxi",
        "sliceToRAS",
        "layoutName",
        "layoutLabel",
        "singletonTag",
        "segmentListFilterEnabled",
        "defaultWriteFileExtension",
    }
)

# Attributes that always hold `key<sep>value` items even without a `|` in them,
# so the key-aware rules below apply (e.g. a single `DICOM.instanceUIDs:...`).
COMPOSITE_ATTRS = frozenset({"attributes", "uids", "voxelValueQuantity", "voxelValueUnits"})

# Composite-item keys whose value is a coding-scheme code, not an identifier.
BENIGN_ITEM_KEYS = frozenset(
    {
        "CodeValue",
        "CodingSchemeDesignator",
        "CodeMeaning",
        "MappedInLayout",
        "SubjectHierarchyVersion",
        "Level",
        "VirtualBranch",
        "Category",
        # NOTE: `segmentID` is deliberately NOT here. Slicer derives a segment id
        # from the source model name, so it carries whatever that name carried.
        "DICOM.SeriesNumber",
        "DICOM.Modality",
        "DICOM.Manufacturer",
        "DICOM.Model",
        "DICOM.PatientSex",
        "DICOM.StudyTime",
        "DICOM.SeriesTime",
        "DICOM.ContentTime",
        "TerminologyEntry",
    }
)

# Composite-item keys whose value is one or more DICOM UIDs.
UID_ITEM_KEYS = frozenset(
    {
        "DICOM",
        "DICOMInstanceUID",
        "DICOM.instanceUIDs",
        "DICOM.StudyInstanceUID",
        "DICOM.SeriesInstanceUID",
        "DICOM.SOPInstanceUID",
        "DICOM.FrameOfReferenceUID",
        "DICOM.ReferencedInstanceUIDs",
        "DICOM.ReferencedImageInstanceUIDs",
    }
)

# Composite-item keys whose value is a direct patient identifier.
IDENTITY_ITEM_KEYS: dict[str, str] = {
    "DICOM.PatientName": CAT_PATIENT_NAME,
    "DICOM.PatientID": CAT_PATIENT_ID,
    "DICOM.PatientComments": CAT_PATIENT_NAME,
    "DICOM.OtherPatientIDs": CAT_PATIENT_ID,
    "DICOM.AccessionNumber": CAT_ACCESSION,
    "DICOM.StudyID": CAT_ACCESSION,
    "DICOM.ReferringPhysicianName": CAT_PATIENT_NAME,
    "DICOM.PerformingPhysicianName": CAT_PATIENT_NAME,
    "MEDSI": CAT_PATIENT_ID,
    "MEDSI.PatientID": CAT_PATIENT_ID,
    "MEDSI.PatientName": CAT_PATIENT_NAME,
}

# Site identity: replaced by a constant, never by a CASE_ token.  A hospital name
# is identical in every scene from that hospital, so giving it a case-scoped
# surrogate would be both wrong and a way to link cases together.
SITE_ITEM_KEYS = frozenset(
    {
        "DICOM.InstitutionName",
        "DICOM.InstitutionAddress",
        "DICOM.InstitutionalDepartmentName",
        "DICOM.StationName",
    }
)
SITE_SURROGATE = "SITE_X"

# Characters that bracket a coding-scheme code value (`SCT^85756007^Tissue`,
# `(DCM,112031,...)`).  A tuple, never a string - see `_is_mrn`.
CODE_DELIMITERS: tuple[str, ...] = ("^", ",")

# Composite-item keys whose value is a DICOM DA (YYYYMMDD).
DATE_ITEM_KEYS = frozenset(
    {
        "DICOM.StudyDate",
        "DICOM.SeriesDate",
        "DICOM.ContentDate",
        "DICOM.AcquisitionDate",
        "DICOM.PatientBirthDate",
        "MEDSI.PatientBirthDate",
    }
)

# NRRD header fields that are structural: never rewritten, always compared after
# a rewrite to prove the geometry survived.
NRRD_STRUCTURAL_FIELDS = (
    "type",
    "dimension",
    "space",
    "sizes",
    "space directions",
    "space origin",
    "kinds",
    "endian",
    "encoding",
    "measurement frame",
    "spacings",
    "thicknesses",
    "axis mins",
    "axis maxs",
    "centerings",
    "labels",
    "units",
    "min",
    "max",
    "old min",
    "old max",
    "data file",
    "datafile",
    "line skip",
    "byte skip",
    "content",
    "sample units",
    "block size",
)


# --------------------------------------------------------------------------- #
# Secret handling
# --------------------------------------------------------------------------- #
def load_or_create_key(key_path: Path, *, allow_create: bool) -> bytes:
    """Return the 32-byte de-identification secret, creating it if permitted.

    The secret is the *only* way to reverse the mapping (MOS-DATA-032/035), so
    generating one silently would be a data-loss bug: the caller is shouted at.
    """
    if key_path.exists():
        raw = key_path.read_text(encoding="ascii").strip()
        try:
            key = bytes.fromhex(raw)
        except ValueError as exc:
            raise ScrubError(
                f"--key-file {key_path} does not contain hex.\n"
                f"Expected 64 hex characters (32 bytes). Parse error: {exc}"
            ) from exc
        if len(key) < 32:
            raise ScrubError(
                f"--key-file {key_path} holds only {len(key)} bytes; at least 32 are required. "
                "Delete it and re-run to mint a fresh key, but be aware that every UID "
                "already mapped under the old key becomes unreachable (MOS-DATA-032: key "
                "rotation is a breaking operation)."
            )
        return key

    if not allow_create:
        raise ScrubError(
            f"--key-file {key_path} does not exist and key creation is disabled in this mode.\n"
            "Run the dry run first (which mints the key) or pass an existing key file."
        )

    key = secrets.token_bytes(32)
    key_path.parent.mkdir(parents=True, exist_ok=True)
    key_path.write_text(key.hex(), encoding="ascii")
    try:
        os.chmod(key_path, stat.S_IRUSR | stat.S_IWUSR)
    except OSError:
        # Windows ACLs do not map onto POSIX mode bits; the warning below stands.
        pass
    sys.stderr.write(
        "\n"
        "!!! ============================================================== !!!\n"
        "!!! A NEW DE-IDENTIFICATION SECRET WAS GENERATED                   !!!\n"
        "!!! ============================================================== !!!\n"
        f"!!!   {key_path}\n"
        "!!! This key is the ONLY way to re-identify anything this tool\n"
        "!!! pseudonymised.  Lose it and every UID mapping is permanently\n"
        "!!! unreachable; leak it and the pseudonymisation is void.\n"
        "!!! Store it OUTSIDE the dataset tree, in a secret store, backed up\n"
        "!!! separately from the data.  Do not commit it.\n"
        "!!! Re-running with a different key mints a DIFFERENT UID space and\n"
        "!!! orphans every result already produced (MOS-DATA-031/032).\n"
        "!!! ============================================================== !!!\n\n"
    )
    return key


def key_fingerprint(key: bytes) -> str:
    """Short public identifier for a key, so reports can be matched to a key file."""
    return hmac.new(key, b"medicalos/deid/key-fingerprint", hashlib.sha256).hexdigest()[:16]


# --------------------------------------------------------------------------- #
# UID mapping - MOS-DATA-032 verbatim, plus the MOS-DATA-033 collision guard.
# --------------------------------------------------------------------------- #
def deid_uid(tenant_deid_key: bytes, source_uid: str) -> str:
    """Deterministic, key-separated, collision-resistant UID surrogate.

    Reproduced from spec MOS-DATA-032 unchanged; output is the DICOM
    `2.25.<uuid-as-integer>` form, at most 44 characters.
    """
    digest = hmac.new(tenant_deid_key, source_uid.encode("ascii"), hashlib.sha256).digest()
    b = bytearray(digest[:16])
    b[6] = (b[6] & 0x0F) | 0x40  # UUID version 4
    b[8] = (b[8] & 0x3F) | 0x80  # RFC 4122 variant
    return "2.25." + str(uuid.UUID(bytes=bytes(b)).int)


class UidMapper:
    """Process-wide source-UID -> surrogate-UID map (MOS-DATA-031/033).

    One instance per run.  Holding it at run scope rather than per file is the
    whole point: the same source UID must come out identical in the scene that
    declares the series and in every scene that merely references it.
    """

    def __init__(self, key: bytes) -> None:
        self._key = key
        self.forward: dict[str, str] = {}
        self._reverse: dict[str, str] = {}
        self.kinds: dict[str, str] = {}
        self.passthrough: set[str] = set()
        self.already_deidentified: set[str] = set()
        self.loaded_rows = 0
        self.lookups = 0
        self.minted = 0

    def load_existing(self, path: Path) -> int:
        """Re-hydrate a previous run's map.

        MOS-DATA-033 makes the map record authoritative and MOS-DATA-032 merely
        the generator that rebuilds it.  Loading it here is what makes a second
        run over already-scrubbed data a no-op instead of a second remapping:
        without it, re-running would mint surrogates *of the surrogates* and
        orphan every reference produced by the first run.
        """
        if not path.exists():
            return 0
        rows = 0
        with path.open("r", encoding="utf-8") as fh:
            for lineno, line in enumerate(fh, 1):
                line = line.strip()
                if not line:
                    continue
                try:
                    obj = json.loads(line)
                except json.JSONDecodeError as exc:
                    raise ScrubError(f"{path}:{lineno}: UID map is not valid JSON Lines: {exc}") from exc
                if "_meta" in obj:
                    continue
                src, dst = obj.get("source_uid"), obj.get("mapped_uid")
                if not src or not dst:
                    raise ScrubError(f"{path}:{lineno}: UID map row missing source_uid/mapped_uid")
                expected = deid_uid(self._key, src)
                if expected != dst:
                    raise ScrubError(
                        f"{path}:{lineno}: UID map row was produced under a different key "
                        f"(ref {short_hash(src)}). Using it now would mix two UID spaces, "
                        "which MOS-DATA-032 forbids. Point --key-file at the matching key."
                    )
                self.forward[src] = dst
                self._reverse[dst] = src
                self.kinds[src] = obj.get("uid_kind", "other")
                rows += 1
        self.loaded_rows = rows
        return rows

    def map_uid(self, source_uid: str, kind: str = "other") -> str:
        """Map one UID, or return it unchanged if it is DICOM-registered."""
        self.lookups += 1
        if source_uid.startswith(DICOM_WELL_KNOWN_UID_ROOT):
            # MOS-DATA-034: SOP class / transfer syntax UIDs are not identifiers.
            self.passthrough.add(source_uid)
            return source_uid
        if source_uid in self._reverse:
            # This is a surrogate we already minted under this key. Leave it.
            self.already_deidentified.add(source_uid)
            return source_uid
        existing = self.forward.get(source_uid)
        if existing is not None:
            if kind != "other":
                self.kinds.setdefault(source_uid, kind)
            return existing
        mapped = deid_uid(self._key, source_uid)
        clash = self._reverse.get(mapped)
        if clash is not None and clash != source_uid:
            # MOS-DATA-033: abort rather than overwrite. A 128-bit HMAC collision
            # here means something is badly wrong, not that we should guess.
            raise ScrubError(
                "UID surrogate collision: two distinct source UIDs derived the same "
                f"surrogate {mapped}. Aborting (MOS-DATA-033). "
                f"refs: {short_hash(source_uid)} and {short_hash(clash)}"
            )
        self.forward[source_uid] = mapped
        self._reverse[mapped] = source_uid
        self.kinds[source_uid] = kind
        self.minted += 1
        return mapped

    def write_map(self, path: Path) -> int:
        """Persist the map as JSON Lines.

        The file holds *plaintext* source UIDs - it is the re-identification
        table (MOS-DATA-033 stores the same thing as AEAD ciphertext in the real
        platform) and must be handled as PHI-equivalent.  Callers are responsible
        for keeping it outside the dataset tree; `resolve_paths` enforces that.
        """
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8", newline="\n") as fh:
            fh.write(
                json.dumps(
                    {
                        "_meta": "medicalos deid_uid_map",
                        "generator": "MOS-DATA-032",
                        "key_fingerprint": key_fingerprint(self._key),
                        "rows": len(self.forward),
                        "warning": "CONTAINS SOURCE UIDS - treat as PHI-equivalent",
                    }
                )
                + "\n"
            )
            for src in sorted(self.forward):
                fh.write(
                    json.dumps(
                        {
                            "source_uid": src,
                            "mapped_uid": self.forward[src],
                            "uid_kind": self.kinds.get(src, "other"),
                        },
                        ensure_ascii=False,
                    )
                    + "\n"
                )
        try:
            os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)
        except OSError:
            pass
        return len(self.forward)


# --------------------------------------------------------------------------- #
# Surrogates for non-UID identifiers
# --------------------------------------------------------------------------- #
def short_hash(value: str, salt: bytes = b"medicalos/deid/unsalted") -> str:
    """Fallback reference used in error messages before the report salt exists."""
    return hashlib.sha256(salt + value.encode("utf-8")).hexdigest()[:12]


def normalise_identity(text: str) -> str:
    """Fold an identity string so trivial spelling variants share a surrogate.

    Case, accents and separator runs vary between the scene XML (`NAME 4923665
    MEDSI`) and the NRRD header (`Name_4923665_MEDSI`); folding them means the
    segment ID keeps referring to the same thing after scrubbing.
    """
    folded = unicodedata.normalize("NFKD", text)
    folded = "".join(ch for ch in folded if not unicodedata.combining(ch))
    folded = folded.casefold()
    folded = re.sub(r"[^0-9a-z\u0400-\u04FF]+", " ", folded)
    return " ".join(folded.split())


class SurrogateRegistry:
    """Stable `CASE_nnnn` tokens, derived from the secret so they survive reruns.

    Identities that co-occur in one value (a name next to its MRN) are unioned,
    so the PatientName attribute and the Segment0_ID string that embeds the same
    MRN collapse onto one token instead of two unrelated ones.
    """

    def __init__(self, key: bytes) -> None:
        self._key = key
        self._parent: dict[str, str] = {}
        self._canonical_rank: dict[str, int] = {}
        self._group_of: dict[str, str] = {}
        self._assigned: dict[str, str] = {}
        self.frozen = False

    # -- union-find over identity cores ------------------------------------ #
    def _find(self, item: str) -> str:
        self._parent.setdefault(item, item)
        root = item
        while self._parent[root] != root:
            root = self._parent[root]
        while self._parent[item] != root:
            self._parent[item], item = root, self._parent[item]
        return root

    def declare(self, core: str, rank: int) -> None:
        """Register an identity core.  Lower rank == better canonical choice."""
        if self.frozen:
            raise ScrubError(
                f"identity core appeared during the apply pass but not during discovery "
                f"(ref {short_hash(core)}). The two passes disagreed, which would emit "
                "inconsistent surrogates; aborting instead."
            )
        self._find(core)
        self._canonical_rank[core] = min(self._canonical_rank.get(core, rank), rank)

    def link(self, cores: Sequence[str]) -> None:
        """Union identity cores observed inside one value."""
        if len(cores) < 2:
            return
        root = self._find(cores[0])
        for other in cores[1:]:
            other_root = self._find(other)
            if other_root == root:
                continue
            # Deterministic merge direction: better rank wins, then lexical order.
            a = (self._canonical_rank.get(root, 99), root)
            b = (self._canonical_rank.get(other_root, 99), other_root)
            keep, drop = (root, other_root) if a <= b else (other_root, root)
            self._parent[drop] = keep
            root = keep

    def finalize(self) -> None:
        """Close discovery and allocate every `CASE_nnnn` token in one shot.

        Allocating here, in sorted group order rather than in file-visit order,
        is what makes the collision fallback reproducible: the token a case gets
        depends only on the key and the set of identities, never on which scene
        happened to be read first.
        """
        groups: dict[str, list[str]] = defaultdict(list)
        for core in self._parent:
            groups[self._find(core)].append(core)
        canonical: dict[str, str] = {}
        for root, members in groups.items():
            members.sort(key=lambda c: (self._canonical_rank.get(c, 99), c))
            canonical[root] = members[0]
        for core in self._parent:
            self._group_of[core] = canonical[self._find(core)]

        taken: dict[str, str] = {}
        for group in sorted(set(canonical.values())):
            digest = hmac.new(self._key, ("case:" + group).encode("utf-8"), hashlib.sha256).digest()
            base = f"CASE_{int.from_bytes(digest[:4], 'big') % 10000:04d}"
            token = base
            if token in taken:
                token = f"{base}_{digest[4:6].hex()}"
                if token in taken:
                    raise ScrubError(
                        f"surrogate collision for {token}; the CASE_ token space is too "
                        "small for this corpus (needs a code change, not a retry)."
                    )
            taken[token] = group
            self._assigned[group] = token
        self.frozen = True

    def surrogate(self, core: str) -> str:
        """Return the `CASE_nnnn` token for an identity core."""
        group = self._group_of.get(core)
        if group is None:
            raise ScrubError(
                f"identity core was never declared during discovery (ref {short_hash(core)}); "
                "refusing to mint an unregistered surrogate."
            )
        return self._assigned[group]

    def date_offset_days(self, core: str, window: int) -> int:
        """Per-case date shift, so intervals inside one case stay exact."""
        group = self._group_of.get(core, core)
        digest = hmac.new(self._key, ("dateshift:" + group).encode("utf-8"), hashlib.sha256).digest()
        span = 2 * window + 1
        return int.from_bytes(digest[:4], "big") % span - window

    @property
    def cases(self) -> int:
        return len(self._assigned)


# --------------------------------------------------------------------------- #
# Findings and reports
# --------------------------------------------------------------------------- #
@dataclass
class Finding:
    """One PHI removal or remap.  `phi_ref` stands in for the value, always."""

    location: str
    category: str
    action: str
    phi_ref: str
    count: int = 1
    surrogate: str | None = None

    def to_json(self) -> dict[str, Any]:
        out = {
            "location": self.location,
            "category": self.category,
            "action": self.action,
            "phi_ref": self.phi_ref,
            "count": self.count,
        }
        if self.surrogate is not None:
            out["surrogate"] = self.surrogate
        return out


@dataclass
class FileResult:
    path: Path
    root_label: str
    rel_path: str
    kind: str
    findings: list[Finding] = field(default_factory=list)
    uids_remapped: int = 0
    changed: bool = False
    backup_path: str | None = None
    error: str | None = None

    @property
    def attributes_changed(self) -> list[str]:
        return sorted({f.location for f in self.findings})

    def to_json(self) -> dict[str, Any]:
        # Count UIDs individually (one finding can cover a list of hundreds) so
        # these numbers add up to the run totals.
        by_cat: Counter[str] = Counter()
        for f in self.findings:
            by_cat[f.category] += f.count if f.category == CAT_DICOM_UID else 1
        return {
            "root": self.root_label,
            "path": self.rel_path,
            "kind": self.kind,
            "changed": self.changed,
            "backup": self.backup_path,
            "uids_remapped": self.uids_remapped,
            "findings_total": len(self.findings),
            "findings_by_category": dict(sorted(by_cat.items())),
            "attributes_changed": self.attributes_changed,
            "findings": [f.to_json() for f in self.findings],
            "error": self.error,
        }


# --------------------------------------------------------------------------- #
# The scrubber
# --------------------------------------------------------------------------- #
@dataclass
class Policy:
    mrn_min_digits: int
    mrn_max_digits: int
    date_mode: str  # shift | redact | keep
    date_shift_window: int
    cyrillic_mode: str  # redact | path-only | keep
    date_min_year: int
    date_max_year: int


class Scrubber:
    """Value-level PHI detection and replacement.

    Two passes over the corpus: `discover=True` only registers identity cores and
    their links, `discover=False` performs replacement.  The split exists so a
    name seen alone in file A gets the same token as the same name seen next to
    its MRN in file B.
    """

    def __init__(
        self,
        *,
        uid_mapper: UidMapper,
        surrogates: SurrogateRegistry,
        policy: Policy,
        report_salt: bytes,
    ) -> None:
        self.uids = uid_mapper
        self.surrogates = surrogates
        self.policy = policy
        self._salt = report_salt
        self.discover = True
        self.link_scope = "file"
        self._case_core: str | None = None  # identity core of the file being scrubbed
        self._file_fallback_core = "unknown"
        self._file_cores: list[str] = []
        self._pending_weak: list[str] = []
        self._file_case: dict[str, str] = {}  # file key -> canonical identity core
        self._file_key = ""

    # -- reporting helpers -------------------------------------------------- #
    def phi_ref(self, value: str) -> str:
        return hmac.new(self._salt, value.encode("utf-8"), hashlib.sha256).hexdigest()[:12]

    def begin_file(self, file_key: str, fallback_core: str) -> None:
        self._file_key = file_key
        self._file_fallback_core = fallback_core
        self._file_cores = []
        self._pending_weak = []
        # In the apply pass the case core is already known from discovery, so a
        # date encountered before the patient node still gets the case's offset.
        self._case_core = None if self.discover else self._file_case.get(file_key)

    def end_file(self) -> None:
        """Close a file: union its identities and remember its canonical core.

        One Slicer scene in these corpora describes one case, so a name found in
        the PatientName attribute and an MRN found in a model name belong to the
        same person even though they never appear in the same string.  With
        --link-scope element that assumption is dropped.

        Weak identities (free-form names, study IDs) are resolved only here,
        *after* the file's strong identifiers are known, and are namespaced by the
        file's case.  Namespacing them matters: an institution name or a StudyID
        of "1" is identical in every scene, and a globally-keyed weak core would
        transitively union every case in the corpus into a single surrogate.
        """
        if not self.discover:
            return
        strong = sorted(set(self._file_cores))
        if self.link_scope == "file" and len(strong) > 1:
            self.surrogates.link(strong)
        if self._case_core is None and strong:
            self._case_core = strong[0]

        case = self._case_core or self._file_fallback_core
        if self._case_core is None and self._pending_weak:
            # No strong identifier in this file: anchor its weak names to the
            # directory, so the scene still gets exactly one CASE_ token.
            self.surrogates.declare(case, 4)
        for norm in sorted(set(self._pending_weak)):
            core = f"name:{case}:{norm}"
            self.surrogates.declare(core, 3)
            self.surrogates.link([case, core])

        if self._case_core is not None or self._pending_weak:
            self._file_case[self._file_key] = case

    def _note_core(self, core: str) -> None:
        self._file_cores.append(core)

    def _weak_core(self, text: str) -> str:
        """Namespace a free-form identity by the file's case (see end_file)."""
        return f"name:{self._case_key()}:{normalise_identity(text)}"

    def _case_key(self) -> str:
        return self._case_core or self._file_fallback_core

    # -- identity cores ----------------------------------------------------- #
    def _identity_cores(self, text: str) -> list[tuple[str, str, int]]:
        """Return (core, category, rank) for every hard identity marker in `text`.

        Rank orders canonical choice: an MRN beats a pseudonym beats a name,
        because the MRN is the value most likely to recur verbatim elsewhere.
        """
        cores: list[tuple[str, str, int]] = []
        claimed: set[str] = set()
        for m in RE_PSEUDONYM.finditer(text):
            cores.append(("svr:" + m.group(0).upper().replace("-", "_"), CAT_PSEUDONYM, 1))
            claimed.update(re.findall(r"\d+", m.group(0)))
        for m in RE_UNNAMED.finditer(text):
            cores.append(("acc:" + m.group(1), CAT_ACCESSION, 2))
            claimed.add(m.group(1))
        for m in RE_DIGIT_RUN.finditer(text):
            digits = m.group(1)
            # `Unnamed - 10193927` is one identifier, not an accession plus an
            # MRN that happen to share digits; counting it twice inflates the
            # report and splits the surrogate across two cores.
            if digits in claimed:
                continue
            if not self._is_mrn(text, m.start(1), m.end(1), digits):
                continue
            cores.append(("mrn:" + digits, CAT_PATIENT_ID, 0))
        return cores

    def _is_mrn(self, text: str, start: int, end: int, digits: str) -> bool:
        """Reject digit runs that are codes or dates rather than record numbers."""
        if not (self.policy.mrn_min_digits <= len(digits) <= self.policy.mrn_max_digits):
            return False
        prev_ch = text[start - 1] if start > 0 else ""
        next_ch = text[end] if end < len(text) else ""
        # SCT^85756007^Tissue and (DCM,112031,...) are coding-scheme code values.
        # The membership test is against a tuple, not a string: `"" in "^,"` is
        # True, which silently exempted every value that was *exactly* a digit
        # run - which is precisely the shape of a bare patient ID.
        if prev_ch in CODE_DELIMITERS and next_ch in CODE_DELIMITERS:
            return False
        if self._looks_like_date(digits):
            return False
        return True

    def _looks_like_date(self, digits: str) -> bool:
        if len(digits) != 8:
            return False
        try:
            year = int(digits[:4])
            if not (self.policy.date_min_year <= year <= self.policy.date_max_year):
                return False
            _dt.date(year, int(digits[4:6]), int(digits[6:8]))
        except ValueError:
            return False
        return True

    # -- date handling ------------------------------------------------------ #
    def _shift_date(self, digits: str) -> str:
        offset = self.surrogates.date_offset_days(self._case_key(), self.policy.date_shift_window)
        try:
            d = _dt.date(int(digits[:4]), int(digits[4:6]), int(digits[6:8]))
        except ValueError as exc:
            raise ScrubError(f"unparseable DICOM DA value (ref {self.phi_ref(digits)}): {exc}") from exc
        return (d + _dt.timedelta(days=offset)).strftime("%Y%m%d")

    def _apply_date(self, digits: str, location: str, out: list[Finding]) -> str:
        if self.policy.date_mode == "keep":
            return digits
        if self.policy.date_mode == "redact":
            new = ""
        else:
            new = self._shift_date(digits)
        out.append(
            Finding(
                location=location,
                category=CAT_DATE,
                action="shift" if self.policy.date_mode == "shift" else "redact",
                phi_ref=self.phi_ref(digits),
                surrogate=new or None,
            )
        )
        return new

    # -- core value scrub --------------------------------------------------- #
    def scrub_value(self, location: str, key: str, value: str) -> tuple[str, list[Finding]]:
        """Scrub one XML attribute or NRRD header field value."""
        if not value or key in SKIP_ATTRS or RE_PURE_NUMERIC.match(value):
            return value, []
        if key == "SegmentationDisplayProperties":
            return self._scrub_segmentation_display(location, value)
        if RE_PATH_ATTR.match(key):
            return self._scrub_path(location, value)
        if key in COMPOSITE_ATTRS or "|" in value or "^" in value:
            return self._scrub_composite(location, value)
        return self._scrub_free(location, key, value)

    # -- composite `a^b|c^d|` / `a:b|c:d` ----------------------------------- #
    @staticmethod
    def _partition_item(item: str) -> tuple[str, str, str]:
        i_caret = item.find("^")
        i_colon = item.find(":")
        candidates = [i for i in (i_caret, i_colon) if i >= 0]
        if not candidates:
            return "", "", item
        i = min(candidates)
        return item[:i], item[i], item[i + 1 :]

    def _scrub_composite(self, location: str, value: str) -> tuple[str, list[Finding]]:
        findings: list[Finding] = []
        parts = value.split("|")
        for idx, item in enumerate(parts):
            if not item:
                continue
            key, sep, val = self._partition_item(item)
            where = f"{location}[{key}]" if key else location
            if key in BENIGN_ITEM_KEYS or not val:
                continue
            if key in UID_ITEM_KEYS:
                new_val, f = self._scrub_uid_list(where, val, kind=_uid_kind_for(key))
            elif key in DATE_ITEM_KEYS:
                new_val, f = self._scrub_date_value(where, val)
            elif key in SITE_ITEM_KEYS:
                new_val, f = self._scrub_site_value(where, val)
            elif key in IDENTITY_ITEM_KEYS:
                new_val, f = self._scrub_identity_value(where, val, IDENTITY_ITEM_KEYS[key])
            else:
                new_val, f = self._scrub_free(where, key, val)
            findings.extend(f)
            if new_val != val:
                parts[idx] = f"{key}{sep}{new_val}" if sep else new_val
        return ("|".join(parts), findings) if findings else (value, [])

    def _scrub_uid_list(self, location: str, value: str, kind: str) -> tuple[str, list[Finding]]:
        tokens = value.split()
        if not tokens:
            return value, []
        mapped_count = 0
        other_changed = False
        findings: list[Finding] = []
        out_tokens: list[str] = []
        for tok in tokens:
            if is_dicom_uid(tok):
                mapped = self.uids.map_uid(tok, kind)
                if mapped != tok:
                    mapped_count += 1
                out_tokens.append(tok if self.discover else mapped)
            else:
                # A `uids="DICOM^<value>"` entry is not always a UID: Slicer puts
                # the patient-level record number there. Dropping this branch's
                # result once left an MRN sitting in the scene.
                sub, sub_findings = self._scrub_free(location, "", tok)
                findings.extend(sub_findings)
                if sub != tok:
                    other_changed = True
                out_tokens.append(sub)
        if mapped_count:
            findings.append(
                Finding(
                    location=location,
                    category=CAT_DICOM_UID,
                    action="remap",
                    phi_ref=self.phi_ref(value if len(tokens) == 1 else f"<{len(tokens)} uids>"),
                    count=mapped_count,
                )
            )
        if self.discover or not (mapped_count or other_changed):
            return value, findings
        return " ".join(out_tokens), findings

    def _scrub_date_value(self, location: str, value: str) -> tuple[str, list[Finding]]:
        digits = value.strip()
        if not (len(digits) == 8 and digits.isdigit()):
            return self._scrub_free(location, "", value)
        findings: list[Finding] = []
        new = self._apply_date(digits, location, findings)
        return new, findings

    def _scrub_site_value(self, location: str, value: str) -> tuple[str, list[Finding]]:
        text = value.strip()
        if not text or text == SITE_SURROGATE or self.discover:
            return value, []
        return SITE_SURROGATE, [
            Finding(
                location=location,
                category=CAT_SITE_TOKEN,
                action="redact",
                phi_ref=self.phi_ref(text),
                surrogate=SITE_SURROGATE,
            )
        ]

    def _scrub_identity_value(self, location: str, value: str, category: str) -> tuple[str, list[Finding]]:
        text = value.strip()
        if not text or RE_NEUTRAL_TOKEN.match(text):
            # Already one of our own tokens: re-pseudonymising it would mint a
            # second surrogate for the same case and break every prior reference.
            return value, []
        cores = self._identity_cores(text)
        if self.discover:
            if cores:
                for c, _cat, r in cores:
                    self.surrogates.declare(c, r)
                    self._note_core(c)
                self.surrogates.link([c for c, _c, _r in cores])
                best = min(cores, key=lambda c: (c[2], c[0]))
                if best[2] <= 1 and self._case_core is None:
                    self._case_core = best[0]
            else:
                # Resolved in end_file(), once the file's strong cores are known.
                self._pending_weak.append(normalise_identity(text))
            return value, []
        core = min(cores, key=lambda c: (c[2], c[0]))[0] if cores else self._weak_core(text)
        token = self.surrogates.surrogate(core)
        return token, [
            Finding(
                location=location,
                category=category,
                action="pseudonymise",
                phi_ref=self.phi_ref(text),
                surrogate=token,
            )
        ]

    # -- SegmentationDisplayProperties: `<encodedSegmentID> Key:val ...|` ---- #
    def _scrub_segmentation_display(self, location: str, value: str) -> tuple[str, list[Finding]]:
        findings: list[Finding] = []
        records = value.split("|")
        for idx, rec in enumerate(records):
            if not rec.strip():
                continue
            head, sep, tail = rec.partition(" ")
            new_head, f = self._scrub_encoded_token(f"{location}[segmentID]", head)
            findings.extend(f)
            if new_head != head:
                records[idx] = new_head + sep + tail
        return ("|".join(records), findings) if findings else (value, [])

    # -- percent-encoded single token --------------------------------------- #
    def _scrub_encoded_token(self, location: str, token: str) -> tuple[str, list[Finding]]:
        """Scrub a token that may be percent-encoded, re-encoding only if changed."""
        if RE_PERCENT_ESCAPE.search(token):
            decoded = urllib.parse.unquote(token)
            new_decoded, findings = self._scrub_free(location, "", decoded)
            if new_decoded == decoded:
                return token, findings
            return urllib.parse.quote(new_decoded, safe=""), findings
        return self._scrub_free(location, "", token)

    # -- paths -------------------------------------------------------------- #
    def _scrub_path(self, location: str, value: str) -> tuple[str, list[Finding]]:
        """Reduce a path to its basename and scrub the basename in turn.

        A Slicer `fileName` is resolved relative to the scene, so a path that
        pointed into the annotator's home directory was already broken for anyone
        else; keeping only the basename loses nothing and removes the directory
        chain, which is where the names, MRNs and institution folders live.
        """
        raw = value
        encoded = bool(RE_PERCENT_ESCAPE.search(raw))
        decoded = urllib.parse.unquote(raw) if encoded else raw
        findings: list[Finding] = []

        has_dir = ("/" in decoded) or ("\\" in decoded)
        basename = re.split(r"[\\/]", decoded)[-1]
        directories = decoded[: len(decoded) - len(basename)]

        if has_dir:
            # Report what was in the directory chain by category rather than
            # lumping it all under "a path was shortened": the operator needs to
            # know an institution token or an MRN was sitting in a folder name.
            dir_cats: list[str] = []
            if RE_USER_HOME.search(directories):
                dir_cats.append(CAT_LOCAL_USER_PATH)
            if RE_CYRILLIC_RUN.search(directories) and self.policy.cyrillic_mode != "keep":
                dir_cats.append(CAT_CYRILLIC_TEXT)
            if RE_SITE_TOKEN.search(directories):
                dir_cats.append(CAT_SITE_TOKEN)
            if RE_UNNAMED.search(directories):
                dir_cats.append(CAT_ACCESSION)
            for _core, cat, _rank in self._identity_cores(directories):
                dir_cats.append(cat)
            if not dir_cats:
                dir_cats.append(CAT_FILESYSTEM_PATH)
            for cat in sorted(set(dir_cats)):
                findings.append(
                    Finding(
                        location=location,
                        category=cat,
                        action="drop_directories",
                        phi_ref=self.phi_ref(decoded),
                    )
                )

        new_base, base_findings = self._scrub_free(location, "", basename)
        findings.extend(base_findings)

        if self.discover:
            return value, []
        if not findings:
            return value, []
        if not has_dir and new_base == basename:
            return value, findings
        return (urllib.parse.quote(new_base, safe="") if encoded else new_base), findings

    # -- free text ---------------------------------------------------------- #
    def _scrub_free(self, location: str, key: str, value: str) -> tuple[str, list[Finding]]:
        """Scrub an unstructured value: markers, UIDs, dates, paths."""
        text = value
        if not text.strip():
            return value, []

        # A value that is itself a path gets path treatment even if its attribute
        # name did not say so (fileListMemberN is covered, but Slicer invents new
        # path-bearing attribute names between versions).
        if RE_PATH_LIKE.search(text) and len(text.split()) == 1 and key != "":
            return self._scrub_path(location, text)

        findings: list[Finding] = []

        # 0. A home-directory path can hide inside a free-form value that is not
        #    itself a path - Slicer stores `ScreenshotDirectory /Users/<login>/...`
        #    as one ScriptedModule parameter, which no path-attribute rule sees.
        if RE_USER_HOME.search(text):
            if not self.discover:
                text = RE_USER_HOME.sub(
                    lambda m: f"{m.group(1)}{m.group(2)}{m.group(1)}{USER_SURROGATE}", text
                )
                findings.append(
                    Finding(
                        location=location,
                        category=CAT_LOCAL_USER_PATH,
                        action="redact",
                        phi_ref=self.phi_ref(value),
                        surrogate=USER_SURROGATE,
                    )
                )

        # 1. Hard identity markers -> the whole value becomes one token.
        cores = self._identity_cores(text)
        site_hit = RE_SITE_TOKEN.search(text)
        cyr_hit = RE_CYRILLIC_RUN.search(text) if self.policy.cyrillic_mode == "redact" else None

        if cores:
            core = min(cores, key=lambda c: (c[2], c[0]))[0]
            if self.discover:
                for c, _cat, r in cores:
                    self.surrogates.declare(c, r)
                    self._note_core(c)
                self.surrogates.link([c for c, _cat, _r in cores])
                best_rank = min(c[2] for c in cores)
                if best_rank <= 1 and self._case_core is None:
                    self._case_core = core
                return value, []
            token = self.surrogates.surrogate(core)
            seen: set[str] = set()
            for _c, cat, _r in cores:
                if cat not in seen:
                    seen.add(cat)
                    findings.append(
                        Finding(
                            location=location,
                            category=cat,
                            action="pseudonymise",
                            phi_ref=self.phi_ref(text),
                            surrogate=token,
                        )
                    )
            if site_hit:
                findings.append(
                    Finding(
                        location=location,
                        category=CAT_SITE_TOKEN,
                        action="pseudonymise",
                        phi_ref=self.phi_ref(site_hit.group(0)),
                        surrogate=token,
                    )
                )
            if _has_name_words(text):
                findings.append(
                    Finding(
                        location=location,
                        category=CAT_PATIENT_NAME,
                        action="pseudonymise",
                        phi_ref=self.phi_ref(text),
                        surrogate=token,
                    )
                )
            ext_match = RE_FILE_EXT.search(text)
            return (token + ext_match.group(1) if ext_match else token), findings

        # 2. Site token or Cyrillic run without an identity core: still PHI, but
        #    there is no identity to anchor a CASE_ token to, so redact in place.
        if site_hit or cyr_hit:
            if self.discover:
                return value, []
            new = RE_SITE_TOKEN.sub("SITE_X", text)
            cat = CAT_SITE_TOKEN if site_hit else CAT_CYRILLIC_TEXT
            if cyr_hit:
                new = RE_CYRILLIC_RUN.sub("TEXT_REDACTED", new)
            findings.append(
                Finding(
                    location=location,
                    category=cat,
                    action="redact",
                    phi_ref=self.phi_ref(text),
                )
            )
            text = new

        # 3. Remap any DICOM UID appearing in free text.
        uid_count = 0

        def _uid_sub(m: re.Match[str]) -> str:
            nonlocal uid_count
            src = m.group(1)
            if not is_dicom_uid(src):
                return src
            mapped = self.uids.map_uid(src, "other")
            if mapped != src:
                uid_count += 1
            return mapped

        text2 = RE_UID.sub(_uid_sub, text)
        if uid_count and not self.discover:
            findings.append(
                Finding(
                    location=location,
                    category=CAT_DICOM_UID,
                    action="remap",
                    phi_ref=self.phi_ref("<free-text uids>"),
                    count=uid_count,
                )
            )
        text = text2

        # 4. Dates embedded in free text (e.g. "CT chest (20231030)").
        if self.policy.date_mode != "keep":
            date_findings: list[Finding] = []

            def _date_sub(m: re.Match[str]) -> str:
                digits = m.group(1)
                if not self._looks_like_date(digits):
                    return digits
                return self._apply_date(digits, location, date_findings)

            text = RE_DIGIT_RUN.sub(_date_sub, text)
            findings.extend(date_findings)

        if self.discover:
            return value, []
        return (text, findings) if findings else (value, [])


def _uid_kind_for(key: str) -> str:
    if key.endswith("StudyInstanceUID"):
        return "study"
    if key.endswith("SeriesInstanceUID"):
        return "series"
    if key.endswith("SOPInstanceUID") or key in ("DICOMInstanceUID", "DICOM.instanceUIDs"):
        return "sop"
    if key.endswith("FrameOfReferenceUID"):
        return "frame_of_reference"
    return "other"


def _has_name_words(text: str) -> bool:
    """True if the value carries capitalised word runs beside its marker."""
    words = re.split(r"[\s_]+", text)
    return sum(1 for w in words if RE_NAME_WORD.match(w)) >= 2


# --------------------------------------------------------------------------- #
# MRML handling
# --------------------------------------------------------------------------- #
def iter_elements(root: ET.Element) -> Iterator[ET.Element]:
    yield root
    for child in root:
        yield from iter_elements(child)


def scrub_mrml(path: Path, scrubber: Scrubber, result: FileResult) -> bytes | None:
    """Parse, scrub and re-serialise one .mrml scene.

    ElementTree is used rather than a regex because a MRML attribute value can
    contain `>` and quoted text, and because attribute *names* vary between
    Slicer versions - we must be able to sweep every attribute of every node, not
    a fixed list.
    """
    try:
        tree = ET.parse(path)
    except ET.ParseError as exc:
        raise ScrubError(f"{path}: not well-formed XML: {exc}") from exc
    root = tree.getroot()

    changed = False
    for el in iter_elements(root):
        for attr_name in list(el.attrib):
            old = el.attrib[attr_name]
            new, findings = scrubber.scrub_value(f"<{el.tag}>@{attr_name}", attr_name, old)
            if findings:
                result.findings.extend(findings)
                result.uids_remapped += sum(f.count for f in findings if f.category == CAT_DICOM_UID)
            if new != old and not scrubber.discover:
                el.attrib[attr_name] = new
                changed = True

    if scrubber.discover or not changed:
        return None

    buf = io.BytesIO()
    # short_empty_elements=False keeps Slicer's `<Tag ...></Tag>` form, so the
    # diff against the original is limited to the values we actually changed.
    tree.write(buf, encoding="UTF-8", xml_declaration=True, short_empty_elements=False)
    data = buf.getvalue()

    # Fail closed: prove the result still parses and still has the same shape.
    try:
        verify_root = ET.fromstring(data)
    except ET.ParseError as exc:
        raise ScrubError(f"{path}: scrubbed XML no longer parses: {exc}") from exc
    if len(list(iter_elements(verify_root))) != len(list(iter_elements(root))):
        raise ScrubError(f"{path}: element count changed during rewrite; refusing to write")
    return data


# --------------------------------------------------------------------------- #
# NRRD handling
# --------------------------------------------------------------------------- #
NRRD_FIELD_RE = re.compile(r"^([^:]+):(=|\s)(.*)$", re.DOTALL)


NRRD_HEADER_READ_CHUNK = 1 << 16
NRRD_HEADER_MAX_BYTES = 8 << 20


def read_nrrd_header(path: Path) -> tuple[bytes, int]:
    """Read only the NRRD header, stopping at the blank line that ends it.

    Reading the whole file here would mean pulling a 290 MB CT volume into memory
    to inspect 3 KB of text, twice (discovery and apply). The header is plain
    ASCII/UTF-8 terminated by a blank line; everything after it is opaque -
    possibly gzip, possibly raw - and is never read unless the file is actually
    rewritten.

    Returns (header_bytes, offset_of_blank_line).
    """
    buf = bytearray()
    with path.open("rb") as fh:
        while True:
            chunk = fh.read(NRRD_HEADER_READ_CHUNK)
            if not chunk:
                raise ScrubError(
                    f"{path}: reached end of file without a blank line terminating the "
                    "NRRD header; refusing to guess where the data starts."
                )
            buf += chunk
            sep = buf.find(b"\n\n")
            if sep >= 0:
                return bytes(buf[:sep]), sep
            if len(buf) > NRRD_HEADER_MAX_BYTES:
                raise ScrubError(
                    f"{path}: no blank line in the first {NRRD_HEADER_MAX_BYTES} bytes; "
                    "this does not look like a NRRD file."
                )


def read_nrrd_data(path: Path, offset: int) -> bytes:
    """Return the data segment verbatim, starting at the header's blank line.

    Never decoded, never re-encoded: the bytes handed back here are written out
    unchanged, which is what guarantees the voxels survive a header rewrite.
    """
    with path.open("rb") as fh:
        fh.seek(offset)
        return fh.read()


def parse_nrrd_header_lines(header: bytes) -> list[tuple[str, str, str, str]]:
    """Return (raw_line, key, separator, value) per header line."""
    out: list[tuple[str, str, str, str]] = []
    for raw in header.decode("utf-8", errors="strict").split("\n"):
        if not raw or raw.startswith("#") or raw.startswith("NRRD"):
            out.append((raw, "", "", ""))
            continue
        m = NRRD_FIELD_RE.match(raw)
        if not m:
            out.append((raw, "", "", ""))
            continue
        key, sep, value = m.group(1), m.group(2), m.group(3)
        if sep == " ":
            # `key: value` - the space is part of the separator, not the value.
            out.append((raw, key, ": ", value))
        else:
            out.append((raw, key, ":=", value))
    return out


def _header_fields_equal(a: Any, b: Any) -> bool:
    if isinstance(a, np.ndarray) or isinstance(b, np.ndarray):
        try:
            return bool(np.array_equal(np.asarray(a), np.asarray(b), equal_nan=True))
        except TypeError:
            return bool(np.array_equal(np.asarray(a), np.asarray(b)))
    if isinstance(a, (list, tuple)) and isinstance(b, (list, tuple)):
        return len(a) == len(b) and all(_header_fields_equal(x, y) for x, y in zip(a, b))
    return bool(a == b)


def scrub_nrrd(path: Path, scrubber: Scrubber, result: FileResult) -> bytes | None:
    """Rewrite only PHI-bearing NRRD *header* fields, byte-preserving the data."""
    header, data_offset = read_nrrd_header(path)
    try:
        lines = parse_nrrd_header_lines(header)
    except UnicodeDecodeError as exc:
        raise ScrubError(f"{path}: NRRD header is not valid UTF-8: {exc}") from exc

    changed = False
    new_lines: list[str] = []
    for raw, key, sep, value in lines:
        if not key or key in NRRD_STRUCTURAL_FIELDS or not value:
            new_lines.append(raw)
            continue
        new_value, findings = scrubber.scrub_value(f"nrrd:{key}", key, value)
        if findings:
            result.findings.extend(findings)
            result.uids_remapped += sum(f.count for f in findings if f.category == CAT_DICOM_UID)
        if new_value != value and not scrubber.discover:
            new_lines.append(f"{key}{sep}{new_value}")
            changed = True
        else:
            new_lines.append(raw)

    if scrubber.discover or not changed:
        return None

    new_header = "\n".join(new_lines).encode("utf-8")

    # Prove the rewrite: every field except the ones we touched must come back
    # byte-identical through pynrrd's own parser, and the data bytes are the
    # *original* object, never re-serialised.
    old_parsed = nrrd.read_header(io.BytesIO(header + b"\n\n"))
    new_parsed = nrrd.read_header(io.BytesIO(new_header + b"\n\n"))
    touched = {f.location.split(":", 1)[1].split("[")[0] for f in result.findings if f.location.startswith("nrrd:")}
    if set(old_parsed) != set(new_parsed):
        raise ScrubError(
            f"{path}: NRRD header field set changed during rewrite "
            f"({sorted(set(old_parsed) ^ set(new_parsed))}); refusing to write."
        )
    for fld in old_parsed:
        if fld in touched:
            continue
        if not _header_fields_equal(old_parsed[fld], new_parsed[fld]):
            raise ScrubError(
                f"{path}: NRRD header field {fld!r} changed during rewrite but was not a "
                "PHI target; refusing to write."
            )
    return new_header + read_nrrd_data(path, data_offset)


# --------------------------------------------------------------------------- #
# Filesystem walk
# --------------------------------------------------------------------------- #
def iter_target_files(root: Path) -> Iterator[Path]:
    for p in sorted(root.rglob("*")):
        if not p.is_file():
            continue
        if SKIP_PATH_PARTS.intersection(p.parts):
            continue
        if p.name.startswith(SKIP_NAME_PREFIXES):
            continue
        suffix = p.suffix.lower()
        if suffix in (".mrml", ".nrrd"):
            yield p


def file_kind(p: Path) -> str:
    if p.suffix.lower() == ".mrml":
        return "mrml"
    if p.name.lower().endswith(".seg.nrrd"):
        return "seg.nrrd"
    return "nrrd"


def path_component_categories(comp: str, scrubber: Scrubber) -> list[str]:
    """Classify one path component.

    Shared by the "not rewritten" inventory and by report-path redaction so the
    two can never disagree - a component reported as carrying an identifier must
    also be the one that gets redacted out of the report text.
    """
    cats: list[str] = []
    if RE_SITE_TOKEN.search(comp):
        cats.append(CAT_SITE_TOKEN)
    if RE_PSEUDONYM.search(comp):
        cats.append(CAT_PSEUDONYM)
    if RE_CYRILLIC_RUN.search(comp):
        cats.append(CAT_CYRILLIC_TEXT)
    if RE_UNNAMED.search(comp):
        cats.append(CAT_ACCESSION)
    if RE_USER_HOME.search("/" + comp + "/"):
        cats.append(CAT_LOCAL_USER_PATH)
    # A Study/Series/SOP Instance UID is a direct identifier under Safe Harbor
    # ("any other unique identifying number"), so a filename that is a UID must
    # not be echoed into the report either.
    stem = comp[: -len(Path(comp).suffix)] if Path(comp).suffix else comp
    if any(is_dicom_uid(m.group(1)) for m in RE_UID.finditer(comp)) or is_dicom_uid(stem):
        cats.append(CAT_DICOM_UID)
    for _core, cat, _rank in scrubber._identity_cores(comp):
        cats.append(cat)
    return sorted(set(cats))


def scan_path_identifiers(
    targets: Sequence[tuple[Path, Path]], paths: "RunPaths", scrubber: Scrubber
) -> list[dict[str, Any]]:
    """Report identifiers that live in file and directory *names*.

    These are NOT rewritten: a Slicer scene's `fileName` attributes and a
    multi-file NRRD's `data file` field point at these names, and renaming them
    from here would silently break every scene that references them.  The
    operator needs to know they exist, so they are reported and excluded from the
    --verify assertion rather than quietly ignored.
    """
    out: list[dict[str, Any]] = []
    seen: set[str] = set()
    for root, p in targets:
        for comp in p.relative_to(root).parts:
            if comp in seen:
                continue
            cats = path_component_categories(comp, scrubber)
            if cats:
                seen.add(comp)
                out.append(
                    {
                        "root": paths.root_labels[root],
                        "component_phi_ref": scrubber.phi_ref(comp),
                        "categories": cats,
                    }
                )
    return out


def redact_rel_path(rel: str, scrubber: Scrubber) -> str:
    """Keep the path actionable but strip PHI-bearing components.

    Directory names in these corpora sometimes carry an institution name in
    Cyrillic; a report that quotes them is a report that leaks.
    """
    parts = []
    for comp in Path(rel).parts:
        cats = path_component_categories(comp, scrubber)
        if cats:
            parts.append(f"<redacted:{','.join(cats)}:{scrubber.phi_ref(comp)}>")
        else:
            parts.append(comp)
    return "/".join(parts)


# --------------------------------------------------------------------------- #
# Run
# --------------------------------------------------------------------------- #
@dataclass
class RunPaths:
    roots: list[Path]
    root_labels: dict[Path, str]
    backup_dir: Path
    key_file: Path
    map_out: Path
    report_out: Path


def _is_within(child: Path, parent: Path) -> bool:
    try:
        child.resolve().relative_to(parent.resolve())
        return True
    except ValueError:
        return False


def resolve_paths(args: argparse.Namespace) -> RunPaths:
    roots = [Path(r).resolve() for r in (args.root or DEFAULTS["roots"])]
    for r in roots:
        if not r.is_dir():
            raise ScrubError(f"--root {r} is not a directory")

    work = Path(args.work_dir).resolve()
    backup_dir = Path(args.backup_dir).resolve() if args.backup_dir else (work / DEFAULTS["backup_subdir"])
    key_file = Path(args.key_file).resolve() if args.key_file else (work / DEFAULTS["key_name"])
    map_out = Path(args.map_out).resolve() if args.map_out else (work / DEFAULTS["map_name"])
    report_out = Path(args.report).resolve() if args.report else (work / DEFAULTS["report_name"])

    # The map and the key ARE the re-identification capability. Inside the dataset
    # tree they would travel with the data and undo the entire exercise.
    for label, p in (("--backup-dir", backup_dir), ("--key-file", key_file), ("--map-out", map_out),
                     ("--report", report_out)):
        for r in roots:
            if _is_within(p, r):
                raise ScrubError(
                    f"{label} ({p}) is inside the dataset root {r}. "
                    "Backups, keys, UID maps and reports must live outside the data they describe."
                )

    labels: dict[Path, str] = {}
    used: set[str] = set()
    for r in roots:
        base = re.sub(r"[^A-Za-z0-9_.-]+", "_", r.name) or "root"
        label, n = base, 1
        while label in used:
            n += 1
            label = f"{base}_{n}"
        used.add(label)
        labels[r] = label
    return RunPaths(roots, labels, backup_dir, key_file, map_out, report_out)


def run(args: argparse.Namespace) -> int:
    paths = resolve_paths(args)
    mode = "verify" if args.verify else ("apply" if args.apply else "dry-run")

    key = load_or_create_key(paths.key_file, allow_create=not args.verify)
    report_salt = hmac.new(key, b"medicalos/deid/report-salt", hashlib.sha256).digest()

    policy = Policy(
        mrn_min_digits=args.mrn_min_digits,
        mrn_max_digits=DEFAULTS["mrn_max_digits"],
        date_mode=args.date_policy,
        date_shift_window=DEFAULTS["date_shift_window_days"],
        cyrillic_mode=args.cyrillic_policy,
        date_min_year=DEFAULTS["date_min_year"],
        date_max_year=DEFAULTS["date_max_year"],
    )
    uid_mapper = UidMapper(key)
    uid_mapper.load_existing(paths.map_out)
    surrogates = SurrogateRegistry(key)
    scrubber = Scrubber(uid_mapper=uid_mapper, surrogates=surrogates, policy=policy, report_salt=report_salt)

    targets: list[tuple[Path, Path]] = []
    for root in paths.roots:
        for p in iter_target_files(root):
            targets.append((root, p))
    if not targets:
        raise ScrubError(f"no .mrml or .nrrd files found under {', '.join(str(r) for r in paths.roots)}")

    # -- pass 1: discovery -------------------------------------------------- #
    scrubber.discover = True
    scrubber.link_scope = args.link_scope
    for root, p in targets:
        scrubber.begin_file(str(p), _fallback_core(root, p))
        throwaway = FileResult(p, paths.root_labels[root], "", file_kind(p))
        try:
            _dispatch(p, scrubber, throwaway)
        except ScrubError:
            raise
        except Exception as exc:  # noqa: BLE001 - re-raised with the file name attached
            raise ScrubError(f"{p}: discovery pass failed: {type(exc).__name__}: {exc}") from exc
        scrubber.end_file()
    surrogates.finalize()
    uid_mapper.lookups = 0
    uid_mapper.minted = 0

    # -- pass 2: apply ------------------------------------------------------ #
    scrubber.discover = False
    results: list[FileResult] = []
    pending_writes: list[tuple[FileResult, bytes]] = []
    for root, p in targets:
        rel = p.relative_to(root).as_posix()
        res = FileResult(p, paths.root_labels[root], redact_rel_path(rel, scrubber), file_kind(p))
        scrubber.begin_file(str(p), _fallback_core(root, p))
        try:
            new_bytes = _dispatch(p, scrubber, res)
        except ScrubError as exc:
            res.error = str(exc)
            results.append(res)
            raise ScrubError(f"aborting: {exc}") from exc
        except Exception as exc:  # noqa: BLE001
            raise ScrubError(f"{p}: apply pass failed: {type(exc).__name__}: {exc}") from exc
        scrubber.end_file()
        if new_bytes is not None:
            res.changed = True
            pending_writes.append((res, new_bytes))
        results.append(res)

    # -- verify mode: no writing, just an assertion -------------------------- #
    exit_code = 0
    if args.verify:
        residual = sum(
            1 for r in results for f in r.findings if f.category in RESIDUAL_CATEGORIES
        )
        if residual:
            exit_code = 2
    elif args.apply:
        exit_code = _perform_writes(pending_writes, paths)
    else:
        for res, _ in pending_writes:
            res.changed = False  # dry run changes nothing on disk

    # -- outputs ------------------------------------------------------------ #
    map_rows = 0
    if not args.verify and uid_mapper.forward:
        map_rows = uid_mapper.write_map(paths.map_out)

    path_ids = scan_path_identifiers(targets, paths, scrubber)
    report = build_report(
        mode, paths, policy, key, results, uid_mapper, surrogates, map_rows, path_ids
    )
    paths.report_out.parent.mkdir(parents=True, exist_ok=True)
    paths.report_out.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    print_summary(report, results, paths, mode)
    return exit_code


def _fallback_core(root: Path, p: Path) -> str:
    """Case key used when a file declares no patient identity of its own."""
    rel_parent = p.parent.relative_to(root).as_posix() or p.parent.name
    return "dir:" + rel_parent


def _dispatch(p: Path, scrubber: Scrubber, res: FileResult) -> bytes | None:
    if p.suffix.lower() == ".mrml":
        return scrub_mrml(p, scrubber, res)
    return scrub_nrrd(p, scrubber, res)


def _perform_writes(pending: list[tuple[FileResult, bytes]], paths: RunPaths) -> int:
    """Back up everything first, then write; abort before any write on conflict."""
    plan: list[tuple[FileResult, bytes, Path]] = []
    for res, data in pending:
        root = next(r for r in paths.roots if _is_within(res.path, r))
        backup = paths.backup_dir / paths.root_labels[root] / res.path.relative_to(root)
        if backup.exists():
            raise ScrubError(
                f"backup target already exists: {backup}\n"
                "Refusing to overwrite a previous backup - the original would become "
                "unrecoverable. Point --backup-dir at a fresh directory."
            )
        plan.append((res, data, backup))

    seen: set[Path] = set()
    for _res, _data, backup in plan:
        if backup in seen:
            raise ScrubError(f"two source files map to the same backup path: {backup}")
        seen.add(backup)

    paths.backup_dir.mkdir(parents=True, exist_ok=True)
    manifest = []
    for res, data, backup in plan:
        backup.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(res.path, backup)
        if backup.stat().st_size != res.path.stat().st_size:
            raise ScrubError(f"backup of {res.path} is truncated; aborting before any write")
        tmp = res.path.with_name(res.path.name + ".deid-tmp")
        try:
            tmp.write_bytes(data)
            os.replace(tmp, res.path)
        finally:
            if tmp.exists():
                tmp.unlink()
        res.backup_path = str(backup)
        manifest.append({"original": str(res.path), "backup": str(backup), "kind": res.kind})
    (paths.backup_dir / "MANIFEST.json").write_text(
        json.dumps({"tool": TOOL_NAME, "version": TOOL_VERSION, "entries": manifest}, indent=2),
        encoding="utf-8",
    )
    return 0


def build_report(
    mode: str,
    paths: RunPaths,
    policy: Policy,
    key: bytes,
    results: list[FileResult],
    uid_mapper: UidMapper,
    surrogates: SurrogateRegistry,
    map_rows: int,
    path_identifiers: list[dict[str, Any]],
) -> dict[str, Any]:
    by_cat: Counter[str] = Counter()
    by_kind: Counter[str] = Counter()
    files_with = 0
    residual = 0
    for r in results:
        by_kind[r.kind] += 1
        if r.findings:
            files_with += 1
        for f in r.findings:
            by_cat[f.category] += f.count if f.category == CAT_DICOM_UID else 1
            if f.category in RESIDUAL_CATEGORIES:
                residual += 1
    return {
        "tool": TOOL_NAME,
        "version": TOOL_VERSION,
        "mode": mode,
        "generated_utc": _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds"),
        "key_fingerprint": key_fingerprint(key),
        "phi_ref_note": (
            "phi_ref is HMAC-SHA256(report_salt, value)[:12]; the report never contains a "
            "PHI value. Two findings with the same phi_ref removed the same string."
        ),
        "roots": [{"label": paths.root_labels[r], "path": str(r)} for r in paths.roots],
        "outputs": {
            "backup_dir": str(paths.backup_dir),
            "key_file": str(paths.key_file),
            "map_out": str(paths.map_out),
            "report": str(paths.report_out),
        },
        "policy": {
            "date_policy": policy.date_mode,
            "cyrillic_policy": policy.cyrillic_mode,
            "mrn_min_digits": policy.mrn_min_digits,
            "mrn_max_digits": policy.mrn_max_digits,
            "date_shift_window_days": policy.date_shift_window,
            "uid_generator": "MOS-DATA-032 2.25.<hmac-sha256 uuid int>",
            "well_known_uid_root_passthrough": DICOM_WELL_KNOWN_UID_ROOT,
        },
        "totals": {
            "files_scanned": len(results),
            "files_by_kind": dict(sorted(by_kind.items())),
            "files_with_findings": files_with,
            "files_written": sum(1 for r in results if r.changed and r.backup_path),
            "findings_total": sum(len(r.findings) for r in results),
            "findings_by_category": {c: by_cat.get(c, 0) for c in ALL_CATEGORIES if by_cat.get(c)},
            "residual_phi_findings": residual,
            "uid_lookups": uid_mapper.lookups,
            "uid_distinct_remapped": len(uid_mapper.forward),
            "uid_loaded_from_map": uid_mapper.loaded_rows,
            "uid_already_deidentified": len(uid_mapper.already_deidentified),
            "uid_wellknown_passthrough": len(uid_mapper.passthrough),
            "uid_map_rows_written": map_rows,
            "case_surrogates": surrogates.cases,
        },
        "verify": {
            "residual_categories": sorted(RESIDUAL_CATEGORIES),
            "residual_phi_findings": residual,
            "passed": residual == 0,
            "note": (
                "date and dicom_uid are excluded from the residual assertion: a shifted "
                "date and a remapped UID are indistinguishable in shape from the originals, "
                "so their presence is not evidence that a file was missed."
            ),
        },
        "residual_path_identifiers": {
            "note": (
                "Identifiers in file/directory NAMES. Not rewritten - Slicer fileName "
                "attributes and NRRD 'data file' fields reference these names, so renaming "
                "them here would break the scenes. Rename as a separate, coordinated step."
            ),
            "distinct_components": len(path_identifiers),
            "components": path_identifiers,
        },
        "files": [r.to_json() for r in results if r.findings or r.error],
    }


def print_summary(report: dict[str, Any], results: list[FileResult], paths: RunPaths, mode: str) -> None:
    t = report["totals"]
    line = "-" * 78
    print(line)
    print(f"{TOOL_NAME} {TOOL_VERSION}   mode={mode}   key={report['key_fingerprint']}")
    print(line)
    for r in report["roots"]:
        print(f"  root {r['label']:<28} {r['path']}")
    print(line)
    print(f"  {'files scanned':<34}{t['files_scanned']:>10}")
    for kind, n in t["files_by_kind"].items():
        print(f"    {kind:<32}{n:>10}")
    print(f"  {'files with findings':<34}{t['files_with_findings']:>10}")
    print(f"  {'files written':<34}{t['files_written']:>10}")
    print(line)
    print(f"  {'category':<34}{'count':>10}")
    print(f"  {'-' * 34}{'-' * 10:>10}")
    for cat in ALL_CATEGORIES:
        n = t["findings_by_category"].get(cat)
        if n:
            print(f"  {cat:<34}{n:>10}")
    print(f"  {'-' * 34}{'-' * 10:>10}")
    print(f"  {'findings total':<34}{t['findings_total']:>10}")
    print(f"  {'of which residual-PHI':<34}{t['residual_phi_findings']:>10}")
    print(line)
    print(f"  {'distinct UIDs in map':<34}{t['uid_distinct_remapped']:>10}")
    print(f"  {'UID lookups':<34}{t['uid_lookups']:>10}")
    print(f"  {'loaded from existing map':<34}{t['uid_loaded_from_map']:>10}")
    print(f"  {'already de-identified (skipped)':<34}{t['uid_already_deidentified']:>10}")
    print(f"  {'well-known UIDs passed through':<34}{t['uid_wellknown_passthrough']:>10}")
    print(f"  {'case surrogates allocated':<34}{t['case_surrogates']:>10}")
    print(line)
    rp = report["residual_path_identifiers"]
    if rp["distinct_components"]:
        cat_counts: Counter[str] = Counter()
        for comp in rp["components"]:
            for c in comp["categories"]:
                cat_counts[c] += 1
        print(f"  NOT REWRITTEN - identifiers in file/directory names: "
              f"{rp['distinct_components']} distinct components")
        for c, n in sorted(cat_counts.items()):
            print(f"    {c:<32}{n:>10}")
        print("    (renaming would break the fileName references inside the scenes)")
        print(line)

    worst = sorted((r for r in results if r.findings), key=lambda r: -len(r.findings))[:10]
    if worst:
        print("  top files by finding count (paths PHI-redacted):")
        for r in worst:
            cats = ",".join(sorted({f.category for f in r.findings}))
            print(f"    {len(r.findings):>6}  {r.root_label}/{r.rel_path}")
            print(f"            {cats}")
        print(line)
    print(f"  report : {paths.report_out}")
    if mode != "verify":
        print(f"  uid map: {paths.map_out}   (PHI-equivalent: contains source UIDs)")
        print(f"  key    : {paths.key_file}  (the ONLY way to re-identify)")
    if mode == "dry-run":
        print("  DRY RUN - nothing was written to the dataset. Re-run with --apply to write.")
    elif mode == "verify":
        residual = t["residual_phi_findings"]
        print(f"  VERIFY - residual PHI findings: {residual}")
        print(f"           (categories asserted on: {', '.join(sorted(RESIDUAL_CATEGORIES))})")
        print("  PASS" if residual == 0 else "  FAIL - exit code 2")
    print(line)


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="scrub_slicer_scenes",
        description=(
            "De-identify 3D Slicer .mrml scenes and .nrrd headers in place. "
            "Dry run by default; --apply is required to write. UIDs are pseudonymised "
            "deterministically (spec MOS-DATA-031/032), never deleted."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "examples:\n"
            "  # survey, write nothing\n"
            "  python scrub_slicer_scenes.py\n"
            "  # survey one tree\n"
            "  python scrub_slicer_scenes.py --root /data/pneumonia\n"
            "  # write, backing every original up first\n"
            "  python scrub_slicer_scenes.py --apply --backup-dir /secure/backup\n"
            "  # prove nothing is left\n"
            "  python scrub_slicer_scenes.py --verify\n"
        ),
    )
    p.add_argument("--root", action="append", metavar="DIR",
                   help="dataset root to scan (repeatable). Default: DEFAULTS['roots'].")
    p.add_argument("--work-dir", default=DEFAULTS["work_dir"], metavar="DIR",
                   help="base directory for key, map, backups and report (default: %(default)s)")
    p.add_argument("--backup-dir", metavar="DIR", help="where originals are copied before --apply")
    p.add_argument("--key-file", metavar="FILE",
                   help="hex secret used for UID and surrogate derivation; generated if absent")
    p.add_argument("--map-out", metavar="FILE", help="UID mapping table (JSON Lines)")
    p.add_argument("--report", metavar="FILE", help="machine-readable JSON report")
    p.add_argument("--apply", action="store_true", help="actually write (default is a dry run)")
    p.add_argument("--verify", action="store_true",
                   help="re-scan and exit non-zero if any residual PHI match remains")
    p.add_argument("--date-policy", choices=("shift", "redact", "keep"), default="shift",
                   help="what to do with DICOM dates (default: %(default)s; shift keeps intervals exact)")
    p.add_argument("--cyrillic-policy", choices=("redact", "path-only", "keep"), default="redact",
                   help="Cyrillic runs: redact everywhere, only inside paths, or keep (default: %(default)s)")
    p.add_argument("--mrn-min-digits", type=int, default=DEFAULTS["mrn_min_digits"], metavar="N",
                   help="shortest standalone digit run treated as a record number (default: %(default)s)")
    p.add_argument("--link-scope", choices=("file", "element"), default="file",
                   help=("whether identities found in one scene are assumed to be one case "
                         "(default: %(default)s). Use 'element' for multi-patient scenes."))
    return p


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.apply and args.verify:
        print("--apply and --verify are mutually exclusive.", file=sys.stderr)
        return 64
    try:
        return run(args)
    except ScrubError as exc:
        print(f"\nERROR: {exc}\n", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
