# SPDX-License-Identifier: Apache-2.0
"""Spec fixtures and the synthetic golden phantom.

THREE SPECS, FOR THREE DIFFERENT JOBS
-------------------------------------
`MOS_IMG_052_DOCUMENT`  the 0.1.0 pleural-effusion spec, transcribed from `MOS-IMG-052`,
                        which calls it "the CI fixture for schema validation". It is
                        REFUSED by `parse_spec`, and that is the correct outcome: see the
                        defect note below.
`MOS_TRAIN_058_DOCUMENT` the lung-lobes spec of `MOS-TRAIN-058`, "the CI fixture for the
                        MONAI serialization round trip". It parses and serializes; it does
                        not EXECUTE in this deployment, because it declares
                        `image_interpolator: bspline3` and a MONAI/torch backend, and
                        `medos.sdk.preprocess` refuses both rather than
                        substituting
                        (`MOS-TRAIN-132`, `MOS-TRAIN-057`).
`selftest_spec()`       a spec this deployment can execute end to end, so that
                        `MOS-TRAIN-133`'s byte-equality check has two tensors to compare.
                        Its golden hash is PINNED below.

TWO SPEC DEFECTS, REPORTED RATHER THAN PAPERED OVER
----------------------------------------------------
1. `MOS-IMG-052` declares `foreground_crop.min_size_voxels: [32, 128, 128]` against
   `patch.size_voxels: [64, 192, 192]`. `MOS-TRAIN-051` requires `min_size_voxels` to be
   element-wise >= `patch.size_voxels` and says "Registration MUST reject a spec that
   violates it". All three axes violate it. The fixture is transcribed unchanged and
   `parse_spec` refuses it, which is what the requirement asks for; "correcting" the
   numbers here would hide a real contradiction between two chapters.
2. `MOS-TRAIN-058` writes `golden_fixture.sha256` and
   `golden_fixture.output_tensor_sha256` as bare hex. `MOS-IMG-049` is explicit: "Every
   field typed `sha256 digest` above is encoded as `"sha256:"` followed by 64 lower-case
   hex characters ... A bare hex string is invalid." The prefix is added here, with this
   note, because the schema is normative over an example of it.

THE PHANTOM
-----------
`MOS-TRAIN-061`: the golden fixture "MUST be a volume the artifact may lawfully
redistribute. It MUST come from a `DatasetVersion` whose `deidentification_status` is
`public_deidentified` and whose licence permits redistribution, or from a synthetic
phantom generated by the pipeline. It MUST NOT come from `clinical`-class ingest under any
consent basis, because the artifact is shipped to sites and to vendors and the fixture
travels with it."

So the fixture is a synthetic phantom, generated by `phantom()` from integer arithmetic
with no random number generator anywhere in it. Every HU value it contains is an integer
and therefore exactly representable in binary32, for the reason
`medos.inference.selftest` gives about its own arithmetic: `MOS-IMG-054` step 5 compares a
SHA-256 for byte equality, so a fixture whose values are not exactly representable makes
the comparison a coin toss in the last ULP and the self-test is switched off within a week.

Spec: MOS-IMG-049, MOS-IMG-052, MOS-IMG-054, MOS-TRAIN-051, MOS-TRAIN-058, MOS-TRAIN-061,
MOS-TRAIN-062, MOS-TRAIN-065, MOS-TRAIN-133.
"""

from __future__ import annotations

import hashlib
from typing import Any

import numpy as np

from medos.sdk.preprocess import RESAMPLER_ID, ChainInput

__all__ = [
    "MOS_IMG_052_DOCUMENT",
    "MOS_TRAIN_058_DOCUMENT",
    "PHANTOM_SHAPE",
    "PHANTOM_SPACING_MM",
    "PHANTOM_AXCODES",
    "PHANTOM_SHA256",
    "GOLDEN_TENSOR_SHA256",
    "GOLDEN_TENSOR_SHAPE",
    "phantom",
    "phantom_input",
    "selftest_spec_document",
]


# =====================================================================================
# MOS-IMG-052, transcribed. REFUSED by parse_spec on MOS-TRAIN-051; see the docstring.
# =====================================================================================
MOS_IMG_052_DOCUMENT: dict[str, Any] = {
    "schema_version": "1.0",
    "id": "prep.pulmo.effusion",
    "version": "1.4.0",
    "model_id": "pulmo.pleural-effusion",
    "model_version": "1.4.0",
    "canonical_geometry": {
        "gantry_tilt": {"mode": "reject", "max_deg": 0.0},
        "non_uniform_spacing": "reject",
        "padding_output_value": -1024.0,
    },
    "orientation_target": "SPL",
    "axis_order": ["k", "j", "i"],
    "target_spacing_mm": [1.5, 0.8, 0.8],
    "image_interpolator": "bspline3",
    "label_interpolator": "nearest",
    "probability_interpolator": "linear",
    "clip": {"min_hu": -1024.0, "max_hu": 600.0},
    "normalisation": {
        "scheme": "zscore_dataset",
        "statistics_source": "spec",
        "mean": -412.73,
        "std": 431.06,
    },
    "foreground_crop": {
        "mode": "threshold_bbox",
        "threshold_hu": -300.0,
        "margin_mm": [10.0, 10.0, 10.0],
        # MOS-TRAIN-051 violation, transcribed unchanged. See the module docstring.
        "min_size_voxels": [32, 128, 128],
    },
    "patch": {
        "size_voxels": [64, 192, 192],
        "sliding_window_overlap": 0.5,
        "blend": "gaussian",
        "gaussian_sigma_scale": 0.125,
        "batch_size": 2,
    },
    "tta": {"axes": [[2]], "reduction": "mean"},
    "io": {
        "input_dtype": "float32",
        "input_layout": "NCDHW",
        "channels": 1,
        "output_kind": "probability",
        "label_set": [
            {"value": 0, "name": "background"},
            {"value": 1, "name": "pleural_effusion_right"},
            {"value": 2, "name": "pleural_effusion_left"},
        ],
    },
    "inverse": {
        "aggregate": "gaussian_weighted_mean",
        "undo_crop": "pad_background",
        "target_grid": "canonical",
        "assert_shape_equal": True,
        "affine_tolerance": 1.0e-4,
    },
    "backend": {"resampler": "SimpleITK==2.3.1", "numpy": "numpy==1.26.4"},
    "golden_fixture": {
        "path": "fixtures/golden_input.nii.gz",
        "sha256": "sha256:4c1f9a2d7e3b085614af92c0d6e8371b5a4029fd8c6e1b3740a95d2ef8137c6b",
        "output_tensor_sha256":
            "sha256:9b2e7d410c5a8f36e1743b92ad60c8f572e14b093d8a6ce751f0b2498c3da7e6",
        "output_shape": [1, 1, 64, 192, 192],
        "recorded_at": "2026-03-11T09:14:22Z",
        "recorded_by_commit": "a91f2c7d5b4e6038fa1c9d2e7b3045861f0ac7d9",
    },
}


# =====================================================================================
# MOS-TRAIN-058, transcribed, with the `sha256:` prefix added per MOS-IMG-049.
# =====================================================================================
MOS_TRAIN_058_DOCUMENT: dict[str, Any] = {
    "schema_version": "1.0",
    "id": "prep.pulmo.lung-lobes",
    "version": "2.1.0",
    "model_id": "pulmo.lung-lobes",
    "model_version": "2.1.0",
    "canonical_geometry": {
        "gantry_tilt": {"mode": "reject", "max_deg": 0.0},
        "non_uniform_spacing": "resample_to_uniform",
        "padding_output_value": -1024.0,
    },
    "orientation_target": "SPL",
    "axis_order": ["k", "j", "i"],
    "target_spacing_mm": [1.5, 1.0, 1.0],
    "image_interpolator": "bspline3",
    "label_interpolator": "nearest",
    "probability_interpolator": "linear",
    "clip": {"min_hu": -1024.0, "max_hu": 300.0},
    "normalisation": {
        "scheme": "zscore_dataset",
        "statistics_source": "spec",
        "mean": -604.12,
        "std": 421.87,
    },
    "foreground_crop": {
        "mode": "threshold_bbox",
        "threshold_hu": -300.0,
        "margin_mm": [5.0, 5.0, 5.0],
        "min_size_voxels": [96, 224, 224],
    },
    "patch": {
        "size_voxels": [96, 192, 192],
        "sliding_window_overlap": 0.5,
        "blend": "gaussian",
        "gaussian_sigma_scale": 0.125,
        "batch_size": 1,
    },
    "tta": {"axes": [], "reduction": "mean"},
    "io": {
        "input_dtype": "float32",
        "input_layout": "NCDHW",
        "channels": 1,
        "output_kind": "label",
        "label_set": [
            {"value": 0, "name": "background"},
            {"value": 1, "name": "lobe_right_upper"},
            {"value": 2, "name": "lobe_right_middle"},
            {"value": 3, "name": "lobe_right_lower"},
            {"value": 4, "name": "lobe_left_upper"},
            {"value": 5, "name": "lobe_left_lower"},
        ],
    },
    "inverse": {
        "aggregate": "gaussian_weighted_mean",
        "undo_crop": "pad_background",
        "target_grid": "canonical",
        "assert_shape_equal": True,
        "affine_tolerance": 1.0e-4,
    },
    "backend": {
        "resampler": "monai==1.4.0;torch==2.4.1+cpu;USE_COMPILED=1;interp=grid_pull",
        "numpy": "numpy==1.26.4",
    },
    "golden_fixture": {
        "path": "medicalos/golden_input.nii.gz",
        "sha256": "sha256:e3f0b7411d8c26a95f04e7b3182cd6a4790fb25ce81a34d7602f9bc45e13a87d",
        "output_tensor_sha256":
            "sha256:17c9a4e0d6b35f82914ea7c0538bd12f64903ae7c58d21b04f7e6a935cd08b2e",
        "output_shape": [1, 1, 96, 192, 192],
        "recorded_at": "2026-07-02T14:06:51Z",
        "recorded_by_commit": "6d0be71a34f95c82e17d40bb95c3a7f2e08d41cb",
    },
}


# =====================================================================================
# The synthetic phantom
# =====================================================================================
PHANTOM_SHAPE: tuple[int, int, int] = (48, 64, 64)       # (K, J, I)
PHANTOM_SPACING_MM: tuple[float, float, float] = (2.0, 1.0, 1.0)
# The phantom is generated already in the model's target orientation, so the chain's
# Orientationd is an identity permutation on it. That is deliberate: a fixture whose
# orientation differs from the target would make the golden hash depend on the reorient
# step's tie-breaks as well as on the resampler's, and MOS-TRAIN-042 tests orientation
# separately, against nibabel's convention, which is the check that actually catches a
# mirrored volume.
PHANTOM_AXCODES = "SPL"


def phantom(
    shape: tuple[int, int, int] = PHANTOM_SHAPE,
) -> np.ndarray:
    """A deterministic chest-like phantom in HU, channel-first `(1, K, J, I)`.

    Integer HU values only -- air -1000, lung -700, soft tissue 40, bone 900 -- so every
    value and every linear combination of two neighbours with a dyadic weight is exactly
    representable in binary32. No RNG, no `numpy.random`, no seed: a seed would make the
    fixture depend on numpy's generator version, and `MOS-EVID-028`'s objection to seeds
    ("a seed is an input to that one evaluation ... it is never the split") applies to a
    fixture for the same reason.
    """
    k, j, i = shape
    kk = np.arange(k, dtype=np.float64)[:, None, None]
    jj = np.arange(j, dtype=np.float64)[None, :, None]
    ii = np.arange(i, dtype=np.float64)[None, None, :]
    ck, cj, ci = (k - 1) / 2.0, (j - 1) / 2.0, (i - 1) / 2.0

    body = (
        ((kk - ck) / (k * 0.42)) ** 2
        + ((jj - cj) / (j * 0.40)) ** 2
        + ((ii - ci) / (i * 0.44)) ** 2
    ) <= 1.0
    lung_left = (
        ((kk - ck) / (k * 0.32)) ** 2
        + ((jj - cj) / (j * 0.26)) ** 2
        + ((ii - ci * 0.55) / (i * 0.20)) ** 2
    ) <= 1.0
    lung_right = (
        ((kk - ck) / (k * 0.32)) ** 2
        + ((jj - cj) / (j * 0.26)) ** 2
        + ((ii - ci * 1.45) / (i * 0.20)) ** 2
    ) <= 1.0
    spine = (
        ((jj - cj * 1.55) / (j * 0.10)) ** 2 + ((ii - ci) / (i * 0.09)) ** 2
    ) <= 1.0

    arr = np.full(shape, -1000.0, dtype=np.float32)
    arr[body] = np.float32(40.0)
    arr[lung_left | lung_right] = np.float32(-700.0)
    arr[spine & body] = np.float32(900.0)
    return np.ascontiguousarray(arr[np.newaxis, ...], dtype=np.float32)


def phantom_input() -> ChainInput:
    """The phantom as a `ChainInput`. `MOS-IMG-054` step 2's "load the fixture"."""
    return ChainInput(
        arrays={"image": phantom()},
        spacing_mm=PHANTOM_SPACING_MM,
        axcodes=PHANTOM_AXCODES,
    )


def phantom_digest() -> str:
    """`MOS-IMG-054` step 1's `sha256(fixture_bytes)`, over the fixture's own bytes."""
    buf = np.ascontiguousarray(phantom(), dtype="<f4").tobytes(order="C")
    return "sha256:" + hashlib.sha256(buf).hexdigest()


# Pinned. `MOS-TRAIN-065`: "The pipeline MUST NOT offer a 're-record the hash' operation,
# because that operation's only effect is to make a real behavioural change pass a test
# designed to catch it." These two constants are therefore literals and not calls: a change
# to the phantom or to the resampler must break a test and be re-pinned by a human who read
# the diff.
#
# RECORDED, not re-recorded. Both values were measured once on the pinned toolchain of
# `requirements-dev.txt` (numpy 1.26.4, CPython 3.11) by running `phantom_digest()` and
# `medos.sdk.preprocess.record_golden(selftest_spec(), phantom_input())` --
# which is
# `MOS-IMG-054` steps 1 through 4 and is the ONLY recorder (`MOS-TRAIN-134`,
# `MOS-IMG-058`). `MOS-TRAIN-065` forbids an OPERATION that re-records them, not the first
# recording; the first recording is how a golden fixture comes to exist at all. What makes
# the prohibition real is that there is no function in this package that writes these
# lines, and `test_curation.py::test_the_golden_hash_has_exactly_one_recorder` asserts the
# literals still reproduce.
PHANTOM_SHA256 = "sha256:75290aeb9d1c386597c7274d1abf8d0edc53519e04325487c01041918ac13675"
GOLDEN_TENSOR_SHA256 = (
    "sha256:99d199e73fe320cf83b2793ab7bced4cda293a113212ccd9262fd09094d78fbb"
)
GOLDEN_TENSOR_SHAPE: tuple[int, int, int, int, int] = (1, 1, 32, 48, 48)


def selftest_spec_document(
    *,
    output_tensor_sha256: str = GOLDEN_TENSOR_SHA256,
    fixture_sha256: str = PHANTOM_SHA256,
) -> dict[str, Any]:
    """A `PreprocessingSpec` this deployment can execute end to end.

    `image_interpolator: linear` and `backend.resampler = RESAMPLER_ID`, because
    `medos.sdk.preprocess` implements spline orders 0 and 1 and refuses order 3
    rather than substituting one (`MOS-TRAIN-132`). Everything else is shaped like the
    lung-lobes spec of `MOS-TRAIN-058`: `output_kind: label` with a laterality-bearing
    label set and `tta.axes: []`, which `MOS-TRAIN-054` requires of exactly that case --
    "a network never trained with left-right mirroring is not [equivariant], and for a
    laterality-bearing `io.label_set` ... it is confidently not".

    `min_size_voxels == patch.size_voxels` on every axis: the tightest form `MOS-TRAIN-051`
    permits, so a change to either shows up here rather than being absorbed by slack.
    """
    return {
        "schema_version": "1.0",
        "id": "prep.medos.selftest-linear",
        "version": "1.0.0",
        "model_id": "medos.selftest-affine",
        "model_version": "1.0.0",
        "canonical_geometry": {
            "gantry_tilt": {"mode": "reject", "max_deg": 0.0},
            "non_uniform_spacing": "reject",
            "padding_output_value": -1024.0,
        },
        "orientation_target": "SPL",
        "axis_order": ["k", "j", "i"],
        "target_spacing_mm": [1.5, 0.8, 0.8],
        "image_interpolator": "linear",
        "label_interpolator": "nearest",
        "probability_interpolator": "linear",
        "clip": {"min_hu": -1024.0, "max_hu": 300.0},
        "normalisation": {
            "scheme": "zscore_dataset",
            "statistics_source": "spec",
            "mean": -600.0,
            "std": 400.0,
        },
        "foreground_crop": {
            "mode": "threshold_bbox",
            "threshold_hu": -300.0,
            "margin_mm": [2.0, 2.0, 2.0],
            "min_size_voxels": [32, 48, 48],
        },
        "patch": {
            "size_voxels": [32, 48, 48],
            "sliding_window_overlap": 0.5,
            "blend": "gaussian",
            "gaussian_sigma_scale": 0.125,
            "batch_size": 1,
        },
        "tta": {"axes": [], "reduction": "mean"},
        "io": {
            "input_dtype": "float32",
            "input_layout": "NCDHW",
            "channels": 1,
            "output_kind": "label",
            "label_set": [
                {"value": 0, "name": "background"},
                {"value": 1, "name": "lung_right"},
                {"value": 2, "name": "lung_left"},
            ],
        },
        "inverse": {
            "aggregate": "gaussian_weighted_mean",
            "undo_crop": "pad_background",
            "target_grid": "canonical",
            "assert_shape_equal": True,
            "affine_tolerance": 1.0e-4,
        },
        "backend": {"resampler": RESAMPLER_ID, "numpy": f"numpy=={np.__version__}"},
        "golden_fixture": {
            "path": "medicalos/golden_phantom.f32",
            "sha256": fixture_sha256,
            "output_tensor_sha256": output_tensor_sha256,
            "output_shape": list(GOLDEN_TENSOR_SHAPE),
            "recorded_at": "2026-09-16T00:00:00Z",
            "recorded_by_commit": "0" * 40,
        },
    }
